### PR TITLE
fix(custom-gitguardian): error invalid token header #2379

### PR DESCRIPTION
**Pull request by ruzell22**
fixes: 2379

related to: #2313 and #1996

### CODE REVIEW

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 Please fix the syntax in the commit message and the pr description: the issue number needs a hash in front of it for it to get parsed correctly.

**Comment by ruzell22** [comment]
Hello @petermetz , this open PR for testing with relation to gitguardian can now be closed as well. Thank you.

**Comment by petermetz** [comment]
> Hello @petermetz , this open PR for testing with relation to gitguardian can now be closed as well. Thank you.

@ruzell22 Closing, thank you!

**Pull request closed without merging**
