### PR TITLE
fix(plugin-htlc-coordinator-besu): add missing HSTS header

### LINKED ISSUE #2763: fix(plugin-htlc-coordinator-besu): missing HSTS Header
## Description
Static source code assessment has picked up a potential vulnerability regarding undefined HSTS header. The potential fix is to include the same following the recommended remediation

## The report from which the above information was summarized
Risk Rating: Medium
Category: Security Misconfiguration

### Description
The web-application does not define an HSTS header, leaving it vulnerable to attack.

### Impact
Failure to set an HSTS header and provide it with a reasonable "max-age" value of at least one year may leave users vulnerable to Man-in-the-Middle attacks

### Remediation Recommendation
• Set the HSTS header either explicitly within application code or using webserver configurations. 
• Ensure the "max-age" value for HSTS headers is set to 31536000 to ensure HSTS is strictly enforced for at least one year. 
• Include the "includeSubDomains" to maximize HSTS coverage, and ensure HSTS is enforced on all sub-domains under the current domain.
• Note that this may prevent secure browser access to any sub-domains that utilize HTTP; however, use of HTTP is very severe and highly discouraged, even for websites that do not contain any sensitive information, as their contents can still be tampered via Man-in-the-Middle attacks to phish users under the HTTP domain.
• Once HSTS has been enforced, submit the web-application's address to an HSTS preload list - this will ensure that, even if a client is accessing the web-application for the first time (implying HSTS has not yet been set by the web-application), a browser that respects the HSTS preload list would still treat the web-application as if it had already issued an HSTS header. Note that this requires the server to have a trusted SSL certificate and issue an HSTS header with a maxAge of 1 year (31536000).

### Affected files (path - line number)

extensions/cactus-plugin-htlc-coordinator-besu/src/main/typescript/web-services/counterparty-htlc-endpoint.ts - 103

## Snapshot of the sourcecode at the time of scan
image

---

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH @petermetz

### PR DESCRIPTION
**Pull request by krisstern**
Closes #2763

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

### CODE REVIEW

**Comment by RafaelAPB** [comment]
Please remove .idea files. Why do we need  that header?

**Comment by krisstern** [comment]
> Please remove .idea files. Why do we need that header?

Similar to the `.vscode/*` for VS Code files above in the same `.gitignore` file, we git ignore the IntelliJ files in the folder `.idea/`. I think this change is acceptable if you already have done something similar for VS Code. I imagine I am not the only developer to use JetBrain products. It would be odd if you do not have it.

**Comment by RafaelAPB** [comment]
@kkaur01 Excuse me, you are absolutely right regarding the .idea dir in gitignore.

**Review by petermetz — CHANGES_REQUESTED** [review]
@krisstern Please 
1. squash the commits together into a single commit
2. Make sure to include an explanation in the commit message on what/why/how/etc. It's OK to copy a lot of that from the original issue if it is already well explained there but it is important to include the information in the commit log as well not just in the private database of GitHub the commercial entity (the GitHub comments)

**Comment by krisstern** [comment]
Hi @petermetz I have rebased the PR to make it all in 1 commit. Also, I have added some descriptive message to the commit message.

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
> Hi @petermetz I have rebased the PR to make it all in 1 commit. Also, I have added some descriptive message to the commit message.

@krisstern Thank you LGTM!

**Review by outSH — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@krisstern One last thing: please fix the commit lint checks that are failing right now. Attaching the failure logs just to make sure you have access to the information on what is going wrong with the commit message.

If you can't figure it out just let me know and I'll help.

[Uploading 2024-04-05T18-31-59-cacti-commit-lint-fail.log…]()

**Comment by krisstern** [comment]
> @krisstern One last thing: please fix the commit lint checks that are failing right now. Attaching the failure logs just to make sure you have access to the information on what is going wrong with the commit message.
> 
> If you can't figure it out just let me know and I'll help.
> 
> Uploading 2024-04-05T18-31-59-cacti-commit-lint-fail.log…

Sure @petermetz! Let me follow up over the next few days.

**Comment by krisstern** [comment]
Hi @petermetz I have made the requested changes. Hopefully I haven't missied anything important. If so, do let me know.

**Comment by petermetz** [comment]
@krisstern This is looking good to me now, thank you very much for the fixes and changes and sorry for the slow reviews!

**Review by petermetz — APPROVED** [review]

**Pull request merged**
