### PR TITLE
test(connector-fabric): move integration tests to use Fabric v2.5.6 AIO

### PR DESCRIPTION
**Pull request by petermetz**
1. This fixes many flakes that we were suffering from before with the
older versions of the AIO image.
2. There could still be other flakes lurking around, but their numbers
should definitely be going down with this change due to the increased
stability of the new AIO image.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by VRamakrishna** [comment]
@petermetz The Weaver test network scripts use Fabric v2.5.0: https://github.com/hyperledger/cacti/blob/main/weaver/tests/network-setups/fabric/dev/Makefile. Do you want this to be upgraded to 2.5.6 too?

**Comment by petermetz** [comment]
> @petermetz The Weaver test network scripts use Fabric v2.5.0: https://github.com/hyperledger/cacti/blob/main/weaver/tests/network-setups/fabric/dev/Makefile. Do you want this to be upgraded to 2.5.6 too?

@VRamakrishna 
If the image itself is stable and the tests are not flaking because of it then I would prioritize it low and put it in the backlog (the task of upgrading it to v2.5.6 or newer).
If the image suffers from instability like our old v.2.2.x images were, then it's higher priority and I'd recommend upgrading ASAP as well.

**Review by izuru0 — APPROVED** [review]
LGTM

**Pull request merged**
