### PR TITLE
feat(cactus-plugin-persistence-ethereum): use openapi ethereum connector

### PR DESCRIPTION
**Pull request by outSH**
- Refactor persistence ethereum plugin to use openapi ethereum connector
    instead of ethereum-socketio.
- Upgrade web3js to 4.X in both persistence plugin and its tests.
- Update persistence plugin dependency list.
- Recompile base token contracts in persistence plugin to match format
    required by ethereum connector (full compilation output, not just ABI)
- Minor fix in ethereum connector to return empty transactions
    array instead of undefined.
- Fix minor runtime issues in geth-test-ledger

Depends on #2631

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Please resolve the merge conflicts and then pass it back for review!
I think the parent PR's commit stuck around in the diff here.

**Review by petermetz — APPROVED** [review]
LGTM

**Pull request merged**
