### PR TITLE
build(plugin-keychain-memory-wasm): upgrade OpenAPI generator to v6.6.0

### LINKED ISSUE #2181: build(plugin-keychain-memory-wasm): upgrade OpenAPI generator to 5.2.1
The current version (5.2.0) of the OpenAPI generator used for generating the Rust server-side code
of the `plugin-keychain-memory-wasm` module should be upgraded to the newer one
that @jagpreetsinghsasan has upgraded in a separate pull request to be `5.2.1`

The upgrade for `plugin-keychain-memory-wasm` is not trivial (e.g. it's not just
about bumping some version number in a config file) because the entire process of
generating the code under `packages/cactus-plugin-keychain-memory-wasm/src/main/rust/generated/openapi/rust-server`
was done through an undocumented and unscripted manual process at the time.

Acceptance criteria:

1. The build still works and the generated code now uses the OpenAPI generator v5.2.1
2. `packages/cactus-plugin-keychain-memory-wasm/src/main/rust/generated/openapi/rust-server/.openapi-generator/VERSION` also shows the updated version number from point 1 above.

### PR DESCRIPTION
**Pull request by solo-daemon**
fix #2181 
steps to reproduce :

```cd packages packages/cactus-plugin-keychain-memory-wasm/```
```npm run generate-rust-server```
then make changes related to PrometheusExporterMetrics
Also, the server expects Option<> type response on api calls but the generated code does not supports that so made changes to support that.

### CODE REVIEW

**Comment by jagpreetsinghsasan** [comment]
Thankyou @solo-daemon for the pull request. Please let us know if you face any issue around this and when this PR can be reviewed for a possible merge. The diff is looking good at the moment !

**Comment by solo-daemon** [comment]
Hi @jagpreetsinghsasan actually at the time of making the PR the code i had not set up the dev container, inside the dev container some modification were required in the existing pr so, I am working on that

**Comment by solo-daemon** [comment]
@outSH @jagpreetsinghsasan this PR is ready for review now

**Comment by petermetz** [comment]
@solo-daemon It's fine for this for now, but for future pull requests please use only lowercase alphanumeric characters and dashes or underscores in the branch names. There are operating systems/software out there which gets people in trouble if their branch names are case sensitive in any way.

**Review by petermetz — CHANGES_REQUESTED** [review]
@solo-daemon Looks good overall but here are a few nits. Please address these and then we should be good to go.

1. Squash the commits into a single one and have the commit subject be what I just changed the pull request title (exact match)
2. Do not include the generated docs in the diff. Either there's some config option in the generator template to exclude them or they can be ignored some other way. Worst case scenario you just remove them from the commit manually.
3. Please make sure to rebase to the latest
4. Please make sure to document the exact terminal command you've used to generate the sources and also include the directory which you were in. This will help reproduce it later by others when we further upgrade the generated code.

**Review by petermetz — CHANGES_REQUESTED** [review]
@solo-daemon Getting closer. You just have tot update the commit message. You updated the pr description which appears to  be the same but completely differently stored unfortunately.

**Comment by petermetz** [comment]
@solo-daemon Are you still working on this? If not, no worries, I'm just doing some housecleaning and this is one of the oldest open pull requests.

**Comment by solo-daemon** [comment]
@petermetz  i changed the commit message to match the pull request description, can you suggest any other changes once or any one's that i didin't got right.

**Review by petermetz — APPROVED** [review]
@solo-daemon It looks good to me now, thank you for the updates!

One more tip for future reference: When you make changes to a pull request in response to a change request of mine then please hit the re-request review button next to my name in the reviewers section on the top right side of the page so that the PR gets put back into my review queue otherwise I might not notice it for a long time that you made changes.

**Review by outSH — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@solo-daemon Sorry for the delays. I checked out the PR, executed your reproduction steps and then did a `cargo build` and it failed with this error:

```sh
$ cargo build
warning: `/home/peter/a/cacti/packages/cactus-plugin-keychain-memory-wasm/src/main/rust/generated/openapi/rust-server/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling openapi_client v2.0.0-rc.2 (/home/peter/a/cacti/packages/cactus-plugin-keychain-memory-wasm/src/main/rust/generated/openapi/rust-server)
error: unnecessary qualification
  --> src/server/mod.rs:82:9
   |
82 |         futures::future::ok(Service::new(
   |         ^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D unused-qualifications` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(unused_qualifications)]`
help: remove the unnecessary path segments
   |
82 -         futures::future::ok(Service::new(
82 +         future::ok(Service::new(
   |

error: could not compile `openapi_client` (lib) due to 1 previous error
```

Could you please confirm that the code in its current state compiles on your machine?
Could you share your exact `rustc` version and `cargo` version?

**Comment by petermetz** [comment]
Closing this due to inactivity. Please feel free to re-open if you find the time to work on it later!

**Pull request closed without merging**
