### PR TITLE
chore(release): publish v2.0.0-alpha.2

### PR DESCRIPTION
**Pull request by sandeepnRES**
- fix: update cargo.lock when upgrading versions using weaver-update-version.sh
- build: hot-fixing the version bumping script by upgrading from prettier
v2.8.8 to v3.0.3 because the latter ships with typescript types out of the
box. Not sure how this was working to begin with while I was testing the
script but here we are. Apologies! - Peter
- fix(protos-sol): delete package line with string pattern matching
- fix(relay): add sh to entrypoint command in dockerfiles

Co-authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Signed-off-by: Sandeep Nishad <sandeep.nishad1@ibm.com>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Comment by sandeepnRES** [comment]
@petermetz `yarn tools:bump-openapi-spec-dep-versions` this command failed on following steps of `release_management.md`, I've messaged in discord with the logs, please help me fix it. Thanks.

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
> @petermetz `yarn tools:bump-openapi-spec-dep-versions` this command failed on following steps of `release_management.md`, I've messaged in discord with the logs, please help me fix it. Thanks.

@sandeepnRES I've updated the PR description to mirror the commit message and I added a line item to the commit message to explain the fix (it was my fault from an earlier PR most likely - sorry about that)

**Comment by petermetz** [comment]
@sandeepnRES I also ran the script that was failing and now all the spec files are bumped to v2.0.0-alpha.2, thank you for the PR!

**Review by izuru0 — APPROVED** [review]
LGTM

**Pull request merged**
