### PR TITLE
feat(besu): remove hard dependency on keychain

### LINKED ISSUE #963: feat(connector): remove hard dependency on keychain
### Description
As a user of Cactus I want to be able to omit using the keychain if I want to so that I can pick and chose what complexity I take on when I decide to use the framework for my project.

https://chat.hyperledger.org/channel/cactus?msg=WgTabjQho3oFGskSa

### Acceptance Criteria
1. Test coverage for both with and without keychain scenarios
2. CI suite passing
3. Avoid depending on shared mutable state, the API server must be horizontally scalable. No file system usage either.

cc: @takeutak @sfuji822 @hartm @jonathan-m-hamilton @AzaharaC @jordigiam @kikoncuo @petermetz @arnab-roy @jagpreetsinghsasan @TonyRowntree @travis-payne

### PR DESCRIPTION
**Pull request by jagpreetsinghsasan**
## Commit to be reviewed

feat(besu): remove hard dependency on keychain  

    Primary Changes
    ---------------
    1. Updated besu connector to remove hard
       dependency on keychain

    Changes required to incorporate 1)
    ----------------------------------
    2. Updated openapi.tpl.json to have non-keychain
       endpoints
    3. Generated code and updated web-services for them
    4. Updated transact( ) and deployContract( ) fx
    5. Added deployContractNoKeychain( ) fx

Fixes https://github.com/hyperledger/cacti/issues/963

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@jagpreetsinghsasan Thank you for reducing the scope of the PR to just the Besu connector. Now we can get down to the details properly.
First order of business is the code-reuse. Right now, in the diff, there's just one more method added to the connector and most of the code of it seems like copy-paste with some minor tweaks. Please investigate if it can be decomposed to smaller utility functions that do not depend on state . An example I added recently is here in these files on how to do code-reuse in this scenario:
- `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/get-block-v1/get-block-v1-impl.ts`
- `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/get-block-v1/get-block-v1-http.ts`
- `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/get-block-v1/get-block-v1-grpc.ts`
- Also within the connector itself:
```typescript
  public async getBlock(
    request: GetBlockV1Request,
  ): Promise<GetBlockV1Response> {
    const ctx = { logLevel: this.logLevel, web3: this.web3 };
    const getBlockV1Response = await getBlockV1Http(ctx, request);
    this.log.debug("getBlockV1Response=%o", getBlockV1Response);
    return getBlockV1Response;
  }
```

**Comment by jagpreetsinghsasan** [comment]
> @jagpreetsinghsasan Thank you for reducing the scope of the PR to just the Besu connector. Now we can get down to the details properly. First order of business is the code-reuse. Right now, in the diff, there's just one more method added to the connector and most of the code of it seems like copy-paste with some minor tweaks. Please investigate if it can be decomposed to smaller utility functions that do not depend on state . An example I added recently is here in these files on how to do code-reuse in this scenario:
> 
> * `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/get-block-v1/get-block-v1-impl.ts`
> * `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/get-block-v1/get-block-v1-http.ts`
> * `packages/cactus-plugin-ledger-connector-besu/src/main/typescript/impl/get-block-v1/get-block-v1-grpc.ts`
> * Also within the connector itself:
> 
> ```ts
>   public async getBlock(
>     request: GetBlockV1Request,
>   ): Promise<GetBlockV1Response> {
>     const ctx = { logLevel: this.logLevel, web3: this.web3 };
>     const getBlockV1Response = await getBlockV1Http(ctx, request);
>     this.log.debug("getBlockV1Response=%o", getBlockV1Response);
>     return getBlockV1Response;
>   }
> ```

This is a nice way to modularize the functions even further, and thus our main connector class looks cleaner. I am currently in the progress of refactoring the code to do the same. I will re-request for review once done and tested.

**Comment by petermetz** [comment]
@jagpreetsinghsasan Good job on reducing the code duplication! I ran it through the copy paste detection and we are down 2% overall for the besu package compared to the main branch!

[jscpd-report-main.zip](https://github.com/user-attachments/files/16203290/jscpd-report-main.zip)

[jscpd-report-feature963c.zip](https://github.com/user-attachments/files/16203289/jscpd-report-feature963c.zip)


Screenshot from 2024-07-13 11-33-27

**Review by petermetz — CHANGES_REQUESTED** [review]
@jagpreetsinghsasan LGTM now, but please 
1. fix the linter errors and also 
2. sneak in a fix for the test case `packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/private-deploy-contract-from-json-cactus.test.ts` where the container image pull of the ledger was accidentally messed up by someone (most likely me) in a different commit and it's failing because of that. Just search in that file for `start(true)` and then replace it with just `start()` so that it does not skip the downloading of the image from the container registry. This is not a change that is related to this PR, but I'm hoping that if you do make that change then the besu connector tests will start passing overall.

**Review by petermetz — CHANGES_REQUESTED** [review]
^^

**Comment by jagpreetsinghsasan** [comment]
Hi @petermetz , I have included the changes you have requested already 
image

**Review by petermetz — APPROVED** [review]

**Pull request merged**
