### PR TITLE
chore(ci): update deprecated GitHub API

### PR DESCRIPTION
**Pull request by ryjones**
Use current version of GitHub action

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@ryjones Please pin the jobs to exact versions. For example for actions/setup-node the latest is `v3.6.0` (same applies to all the other ones)

**Review by petermetz — APPROVED** [review]
@ryjones LGTM thank you

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by sandeepnRES — APPROVED** [review]

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by sandeepnRES** [comment]
I did `update with rebase` and now I don't know why but it is now showing previously merged commits in this PR

**Comment by petermetz** [comment]
> I did `update with rebase` and I don't know why but it is now showing previously merged commits in this PR

@sandeepnRES My best guess is that you did a pull with merge by accident locally at some point before you did that `update with rebase` and then those commits ended up on the PR branch because of. Cannot be sure though. 

With that said, the 2 other commits were successfully disappeared when Ry hit 'rebase and merge' (I assume) so luckily we did not mess up and duplicate the commits.

**Pull request merged**
