### PR TITLE
test: jestify remote-plugin-imports test

### PR DESCRIPTION
**Pull request by awadhana**
Migrated test from Tap to Jest.

File Path:
packages/cactus-cmd-api-server/src/test/typescript/
integration/remote-plugin-imports.test.ts

This is a PARTIAL resolution to issue #238 

Signed-off-by: awadhana awadhana2021@gmail.com

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@awadhana LGTM

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@awadhana Please fix the DCO

**Review by petermetz — CHANGES_REQUESTED** [review]
Note to self: need to fix the handle leaking in the test case:

```sh
 NodeJS API server + Rust plugin work together
    ✓ NodeJS API server + Rust plugin work together (167 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        52.903 s
Ran all test suites matching /packages\/cactus-cmd-api-server\/src\/test\/typescript\/integration\/remote-plugin-imports.test.ts/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

**Review by jagpreetsinghsasan — APPROVED** [review]

**Comment by petermetz** [comment]
Closing down just to de-clutter the PR queue. Happy to reopen it anytime in the future!

**Pull request closed without merging**
