### PR TITLE
chore(docs): fix dci-lint failure

### PR DESCRIPTION
**Pull request by ryjones**
Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Comment by ryjones** [comment]
@petermetz this is to fix the spurious DCI lint failures

**Comment by petermetz** [comment]
Suggested edit:
```diff
diff --git a/.dcilintignore b/.dcilintignore
index 882b80506..43fd965ea 100644
--- a/.dcilintignore
+++ b/.dcilintignore
@@ -26,3 +26,5 @@ weaver/core/network/corda-interop-app/interop-workflows/src/main/kotlin/org/hype
 
 # Corda test network files that are generated and therefore cannot be altered to comply with DCI-Lint
 weaver/tests/network-setups/corda/shared
+# Commit messages snuck disallowed terminology into the changelog files.
+CHANGELOG.md
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 3188249bf..3c7413dff 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -14,7 +14,7 @@ See [Conventional Commits](https://conventionalcommits.org) for commit guideline
 * **git:** broken line endings corrupt git index after weaver merge ([3998ac3](https://github.com/hyperledger/cacti/commit/3998ac3f66dc7c6659583aed64690ebd8812bd7b)), closes [#2302](https://github.com/hyperledger/cacti/issues/2302)
 * link in fabric cli readme ([e14ae88](https://github.com/hyperledger/cacti/commit/e14ae88341dbc5544568e5ac3ebe41568dae280c))
 * logger bug ([122c203](https://github.com/hyperledger/cacti/commit/122c20382fe1ad46d74669d67f3fc5b71e970fbd))
-* rename primary branch to main; rename allowlist ([81e2f9e](https://github.com/hyperledger/cacti/commit/81e2f9ee95f9a0d34090d32966a502018ccbe643))
+* rename master to main; whitelist to allowlist ([81e2f9e](https://github.com/hyperledger/cacti/commit/81e2f9ee95f9a0d34090d32966a502018ccbe643))
 * update ts version; besu-cli sdk imports; added packages test for besu asset exchange in workflow ([ca494b5](https://github.com/hyperledger/cacti/commit/ca494b52ac34e0e8785ca6231dd29695d7584818))
 * workflow besu asset exchange ([2153df8](https://github.com/hyperledger/cacti/commit/2153df89de06f5a725889289254ddde235f1ab74))
 

```

**Review by petermetz — CHANGES_REQUESTED** [review]
@ryjones Please see the above suggestion

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM, thankyou for the PR

**Review by sandeepnRES — APPROVED** [review]

**Review by petermetz — APPROVED** [review]
@ryjones LGTM, thank you for the updates!

**Pull request merged**
