### PR TITLE
docs(weaver): Fixed broken links in, and referring to, Weaver RFCs

### PR DESCRIPTION
**Pull request by VRamakrishna**
The Weaver RFCs (`weaver/rfcs/`) contain several cross-specification links as relative paths rather than absolute URLs.
Some RFCs are also referenced in other parts of the `weaver` code.
The last refactoring of the `weaver/rfcs/` folder resulted in several broken links. This PR identifies and fixes those links.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@VRamakrishna LGTM, but a small nit-pick is that I'd say `docs(weaver): fix broken links in, and referring to, Weaver RFCs` because in the release the `"fix"` prefixed commits will show up in the "Bug-fixes" section of the release notes and the readers of those documents are people who are trying to decide if they should upgrade their existing production deployments to the newer version or not and to them the documentation fixes (even they ARE fixes in my opinion as well) are not useful info because they are interested in seeing the bug-fixes the code that is running on their servers has received.

Approving it anyway because it's a small thing, but I figured at least I'll write this down here so that you are aware of how the release notes/changelog.md file generation works based on the commit messages.

**Comment by VRamakrishna** [comment]
@petermetz Fixed the title.

**Review by izuru0 — APPROVED** [review]

**Comment by petermetz** [comment]
> @petermetz Fixed the title.

@VRamakrishna Thank you! The **PR title** looks good, but it does not automatically sync to the **commit subject** unfortunately (which is still the old one)

**Comment by VRamakrishna** [comment]
@petermetz Sorry for my misunderstanding. I've amended the commit and pushed again.

**Pull request merged**
