### PR TITLE
docs(readme): fix scope of project typos: workflows, different

### PR DESCRIPTION
**Pull request by 404Nikhil**
workfows -> workflows
differemt -> different

### CODE REVIEW

**Review by izuru0 — COMMENTED** [review]
thanks for correcting typos. the updates themselves looks good to me

before approving this PR, my request is that the commit message is changed to abide by [Conventional Commits syntax](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification). see [PR Checklist - Contributor/Developer](https://github.com/hyperledger/cacti/blob/main/CONTRIBUTING.md#pr-checklist---contributordeveloper)

**Review by petermetz — CHANGES_REQUESTED** [review]
@404Nikhil LGTM on the diff, but please make sure to have the commit subject mirror what I had just updated the PR title to.
This way the commit subject is much more likely to be and stay unique among other commit log entries long term.
The problem with "updated x file" type of commit subjects is that they convey very little information about what happened and why.
Fixing simple typos is not something where repetitive commit subject lines would cause huge confusion of course, but nevertheless I'd like to try and keep with our conventions as much as possible because a healthy commit log helps a LOT down the line when we have trace what changes were made over time and why.

If you need any help with the basic git mechanics (amend, rebase, etc.) then refer to the contributing.md guilde and if that isn't enough to get you over the line then I'm happy to step in and help as well!

**Comment by 404Nikhil** [comment]
hey @petermetz thank you for your detailed instruction and a quick review. I have done the suggested changes can you please review them again.

**Review by petermetz — CHANGES_REQUESTED** [review]
@404Nikhil No worries, thanks again for contributing to the project!
The PR title and the commit message subject still do not match though, so please fix that first!

**Comment by 404Nikhil** [comment]
@petermetz is it matching now?

**Review by petermetz — CHANGES_REQUESTED** [review]
@404Nikhil The subject line is now good (it matches the PR title) but you've removed the rest of the commit message somehow (body, footer).
Please put those back, especially the sign-off and then we should be good to go.

**Comment by jagpreetsinghsasan** [comment]
@404Nikhil lgtm. Please address the above review comments from @petermetz 
Let me know if you need help with anything around this.

**Pull request closed without merging**
