### PR TITLE
fix: Upgrade dependencies in Cargo.toml file for cactus-plugin-keychain-vault package

### PR DESCRIPTION
**Pull request by Poonam1607**
…atements in cactus-plugin-keychain-vault package

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@Poonam1607 This does not appear to do anything to the dependency versions. The only change I see in the diff is you fiddling with some parentheses.

**Comment by Poonam1607** [comment]
I did changes in dependency version.
Screenshot 2023-04-05 at 9 13 31 AM
976234-f7767a3d-ff41-43e2-934e-71d653eef913.png)

**Comment by petermetz** [comment]
> I did changes in dependency version.

@Poonam1607 I believe that you made those changes *somewhere* but they are definitely not in the diff that you pushed to the remote ;-)

**Comment by Poonam1607** [comment]
> > I did changes in dependency version.
> 
> @Poonam1607 I believe that you made those changes _somewhere_ but they are definitely not in the diff that you pushed to the remote ;-)

I am doing it again with a new pull request.

**Comment by petermetz** [comment]
> I am doing it again with a new pull request.

@Poonam1607 Please do not duplicate pull requests. Just fix the existing one instead.

**Comment by Poonam1607** [comment]
I have deleted the existing branch and closed the PR. What should I do now? Suggest please @petermetz

**Comment by petermetz** [comment]
> I have deleted the existing branch and closed the PR. What should I do now? Suggest please @petermetz

@Poonam1607 Recreate the branch, then re-open the PR

**Comment by Poonam1607** [comment]
I recreated the branch with the same name which I have deleted earlier, but the reopen button is still grey out, it's only showing compare and pull request. Can I go with that?

**Pull request closed without merging**
