### PR TITLE
feat(cbdc-bridging): add frontend code for the CBDC example

### PR DESCRIPTION
**Pull request by AndreAugusto11**
* UI to interact with the CBDC example backend

This PR closes one action pointed out in PR #2185

Signed-off-by: André Augusto <andre.augusto@tecnico.ulisboa.pt>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@AndreAugusto11 Please integrate the package into the monorepo, right now it seems completely independent (build scripts, name, version, lock file, etc.).
The easiest way (to me at least) to get it done is to 
1. copy paste an existing package as a whole and then 
2. throw out the source code of it and 
3. put in the one you are contributing
4. ensure everything was renamed as needed (free text search, check both lower case, upper case, snake, camel case etc.)

This usually guarantees that I don't forget things that the CI don't explicitly check for.

**Comment by AndreAugusto11** [comment]
> @AndreAugusto11 Please integrate the package into the monorepo, right now it seems completely independent (build scripts, name, version, lock file, etc.). The easiest way (to me at least) to get it done is to
> 
> 1. copy paste an existing package as a whole and then
> 2. throw out the source code of it and
> 3. put in the one you are contributing
> 4. ensure everything was renamed as needed (free text search, check both lower case, upper case, snake, camel case etc.)
> 
> This usually guarantees that I don't forget things that the CI don't explicitly check for.

@petermetz thanks for the reminder. The code is all in js (not ts) is there a problem with that? Is there already any js package that I can base myself on (I'm expecting some configs to be different)?

**Review by petermetz — APPROVED** [review]
@AndreAugusto11 Sorry for the slow response!
I made the monorepo integration at least on the level that the yarn install in the root will now install the dependencies of this one as well.
I also fixed the build (it would fail due to linter issues)
and updated the package.json metadata to have cacti instead of cactus, etc.

Verified that it works with the back-end that we already had in the codebase.

JS only code: Well, it would be nice to migrate it to TS but I'm also very short on time and trying to balance good enough vs. perfection as usual, so let's just go ahead and merge this in now that it does work and is technically part of the monorepo (even though some of the conventions are not yet followed)

Huge thanks for the contribution this helps a lot!

**Comment by AndreAugusto11** [comment]
> @AndreAugusto11 Sorry for the slow response! I made the monorepo integration at least on the level that the yarn install in the root will now install the dependencies of this one as well. I also fixed the build (it would fail due to linter issues) and updated the package.json metadata to have cacti instead of cactus, etc.
> 
> Verified that it works with the back-end that we already had in the codebase.
> 
> JS only code: Well, it would be nice to migrate it to TS but I'm also very short on time and trying to balance good enough vs. perfection as usual, so let's just go ahead and merge this in now that it does work and is technically part of the monorepo (even though some of the conventions are not yet followed)
> 
> Huge thanks for the contribution this helps a lot!

@petermetz thank you very much, as usual!! 💯💯

I believe it would not be hard to migrate to TS, so I will try to work on that once I have some spare time.

**Pull request merged**
