### PR TITLE
chore: adding custom gitguardian check

### PR DESCRIPTION
**Pull request by ruzell22**
related to #720

this includes gitguardian workflow + configuration file

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Comment by ruzell22** [comment]
Gitguardian scan is not getting triggered when changed to pull_request_target from the original pull_request. Currently figuring out how to make the workflow triggered.

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by ruzell22** [comment]
By default, the environmental secrets is not being accessed by this pull request because it is from a fork repository. However, I have tested it with an exposed test token in replacement with the secrets.GITGUARDIAN_API_KEY and the scanner worked successfully (screenshots are sent to @petermetz privately).

After the PR is merged, it is expected to have access with the environmental secrets and the scanner will run successfully.

The test codes used in testing were all deleted to prevent further usage of it. The PR for the clean up of #720 will be made after this PR is merged.

**Comment by ruzell22** [comment]
Hello @petermetz , commit is now squashed into one and the commit message is also changed. Thank you.

**Review by petermetz — APPROVED** [review]
Great, thank you @ruzell22 LGTM

**Pull request merged**
