### PR TITLE
feat(connector-go-ethereum): add getBlock and getTransactionReceipt methods to connector

### PR DESCRIPTION
**Pull request by rwat17**
- getBlock and getTransactionReceipt added in go-ethereum-socketio-connector
- Added nullish coalescing in monitor options

Closes: #2255
Signed-off-by: tomasz awramski <tomasz.awramski@fujitsu.com>

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by takeutak** [comment]
@petermetz @jagpreetsinghsasan Could you review it?

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by petermetz — APPROVED** [review]
@rwat17 Thank you, LGTM!

**Review by petermetz — CHANGES_REQUESTED** [review]
@rwat17 Oops, my bad, please fix the merge conflicts (otherwise it LGTM)

**Comment by rwat17** [comment]
@petermetz I am sorry you had to wait that long. Done ✔

**Review by petermetz — APPROVED** [review]
@rwat17 I'm also sorry for the laggy review! LGTM, thanks for fixing the conflicts!

**Comment by rwat17** [comment]
@petermetz No problem :) 
Rebased with main.

**Pull request merged**
