### PR TITLE
fix(weaver): upgraded Corda dependencies to overcome Log4j vulnerability

### PR DESCRIPTION
**Pull request by VRamakrishna**
- Updated Corda package dependencies from 4.8 to 4.8.11, in which the vulnerability was fixed.
- Upgraded Gradle from 5.6.4 to 7.5 to manage the Corda updates.
- Downloaded Clikt dependency directly from Maven Central to avoid variant ambiguities in Corda Simple Application.
- Fixed formatting in shell scripts to ensure that the shell command directive was in Line 1.

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]

**Review by sandeepnRES — APPROVED** [review]
Looks good to me.

**Review by outSH — APPROVED** [review]

**Comment by VRamakrishna** [comment]
I need to fix a failing unit test. Am testing the fix out now (requires minor upgrades to the Kotlin and Corda plugin versions). Will merge after I see that test (and other Weaver tests) pass.

**Comment by petermetz** [comment]
@VRamakrishna If the changes in those two commits that you have in the PR right now are broken separately, then please s quash  them together. The guiding principle being that if you check out any specific commit from the main branch then the build should be working regardless of which commit you've picked.

**Comment by VRamakrishna** [comment]
@petermetz I fixed the Weaver tests and squashed the commits, but there is still a blocking error in "Cactus CI / yarn_codegen":
image

See https://github.com/hyperledger/cacti/actions/runs/7580285585/job/20645864623?pr=2980 for error logs. I don't believe my changes have anything to do with this. Can you check?

**Comment by outSH** [comment]
> @petermetz I fixed the Weaver tests and squashed the commits, but there is still a blocking error in "Cactus CI / yarn_codegen": image
> 
> See https://github.com/hyperledger/cacti/actions/runs/7580285585/job/20645864623?pr=2980 for error logs. I don't believe my changes have anything to do with this. Can you check?

The following files are getting changed by `yarn run codegen` (don't ask me why, it seem that changes in gradle depencies in weaver bubbles up to other projects in monorepo):
``` sh
 M examples/cactus-example-carbon-accounting-business-logic-plugin/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M examples/cactus-example-supply-chain-business-logic-plugin/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M extensions/cactus-plugin-object-store-ipfs/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-cmd-api-server/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-core-api/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-consortium-manual/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-htlc-eth-besu-erc20/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-keychain-aws-sm/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-keychain-azure-kv/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-keychain-google-sm/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-keychain-memory-wasm/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-keychain-memory/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-keychain-vault/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-ledger-connector-corda/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-ledger-connector-fabric/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
 M packages/cactus-plugin-odap-hermes/src/main/kotlin/generated/openapi/kotlin-client/gradlew.bat
```

**Comment by VRamakrishna** [comment]
@outSH Thanks for pointing that out. I suspect my `.gitattributes` change may be behind this. Let me revise that and see.

**Comment by VRamakrishna** [comment]
@petermetz @outSH I had to fix some conflicts in a file that was modified by another PR 3 days ago, but after doing so, I'm getting an error in the `yarn_codegen` workflow again. This time is throws an error in a specific package which I never touched. The `.gitattributes` file was also not changed. So I don't know how to debug this. Can you help? The link to the failing workflow: https://github.com/hyperledger/cacti/actions/runs/7610446051/job/20723809720?pr=2980.

**Comment by petermetz** [comment]
> @petermetz @outSH I had to fix some conflicts in a file that was modified by another PR 3 days ago, but after doing so, I'm getting an error in the `yarn_codegen` workflow again. This time is throws an error in a specific package which I never touched. The `.gitattributes` file was also not changed. So I don't know how to debug this. Can you help? The link to the failing workflow: https://github.com/hyperledger/cacti/actions/runs/7610446051/job/20723809720?pr=2980.

@VRamakrishna Some changes got snuck in that triggered the codegen race conditions again.

For now the way I've been dealing with it myself is to just re-try that one specific job and usually it goes through the second time but if not the third time did it so far so I never had to do it a forth time.
Also, make sure not to retry the entire CI execution, just the specific job:

image

**Pull request merged**
