### PR TITLE
chore(github): shorten ci.yaml workflow and job names

### PR DESCRIPTION
**Pull request by zondervancalvez**
### **Commit** to be reviewed
---
chore(github): shorten ci.yaml workflow and job names
```
Primary Changes
----------------
ce - cactus-example
cp - cactus-plugin
cpk - cactus-plugin-keychain
cpl - cactus-plugin-ledger
cplc - cactus-plugin-ledger-connector
plc - plugin-ledger-connector
cpp - cactus-plugin-persistence
ct - cactus-test
ctp - cactus-test-plugin
```
Fixes: hyperledger#2624

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by outSH — APPROVED** [review]

**Comment by sandeepnRES** [comment]
Hi @zondervancalvez May be it'd good if you can add the short-full form mappings (whatever you have in description) as comment in the `ci.yaml`? Just for anyone new trying to contribute.

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
@zondervancalvez Thank you for this! Please resolve the merge conflicts and then we should be good to go (I see that the comments with the mappings are already added as requested by @sandeepnRES so I'm assuming that is taken care of)

**Review by sandeepnRES — APPROVED** [review]
Thanks @zondervancalvez LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@zondervancalvez Please resolve the merge conflicts that just arose!

**Comment by zondervancalvez** [comment]
> @zondervancalvez Please resolve the merge conflicts that just arose!

Conflicts has been addressed

**Comment by petermetz** [comment]
@zondervancalvez OK, thank you. Next time please also hit the re-request review button otherwise it doesn't show up in my review queue.

**Review by petermetz — APPROVED** [review]

**Pull request merged**
