### PR TITLE
feat(iroha): adding checkEmpty param to request

### PR DESCRIPTION
**Pull request by travis-payne**
Depends on #1957

Current functionality did not make use of the newer additional parameter in the Iroha command

Closes: #1265
Signed-off-by: Travis Payne <travis.payne@accenture.com>

### CODE REVIEW

**Comment by petermetz** [comment]
> @petermetz Currently the request params are accepted using an array of params, instead of named, typed params, generated using the OpenAPI. What's your opinion on refactoring this as part of the PR, also makes the optionality of the `oldValue` param a lot cleaner.

@travis-payne I agree. If we don't already have a separate task (so not within the scope of this) for the params refactor, we should (IIRC we did have a task for it though).

**Review by petermetz — COMMENTED** [review]
@travis-payne Were you able to run the tests successfully with these changes? (Right now the tests are being skipped by default so the CI passing doesn't guarantee correctness)

**Review by takeutak — APPROVED** [review]

**Comment by petermetz** [comment]
Rebased this onto upstream/main.
Will still need to verify that it actually works with the tests, but for that we first need the Iroha tests to be passing again.

**Comment by takeutak** [comment]
@petermetz This pull-request has been left unreviewed for a long time.  What would you like to do? (still wait / close this PR / etc.)
I guess that this pull request can no longer be merged to the current branch because it has been a long time.

**Comment by petermetz** [comment]
> @petermetz This pull-request has been left unreviewed for a long time. What would you like to do? (still wait / close this PR / etc.)
> I guess that this pull request can no longer be merged to the current branch because it has been a long time.

@takeutak Agreed on all of those points. Let's close this down for now and if there's willingness for someone to take it over the finish line then we can re-open it anytime we want. Closing it for now to de-clutter the PR queue a little bit more.

**Review by petermetz — COMMENTED** [review]
TODO: Manually verify that the tests are passing with these changes.

**Pull request closed without merging**
