### PR TITLE
refactor(cmd-api-server): clean up configuration parameters #720

### PR DESCRIPTION
**Pull request by ruzell22**
fixes: #720

Parameters that are cleaned up are: cactusNodeId, consortiumId, keychainSuffixKeyPairPem
Parameter keyPairPem cannot be remove as it results to an error in running the api server.

Cleaning the three mentioned parameter are backwards compatible with tags versions:
v1.0.0-rc.3 and v1.0.0
The latest tag being used as of this change is v1.0.0-25-gdda3f00c

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 The documentation doesn't seem to be updated. Please go through the acceptance criteria again.

**Comment by ruzell22** [comment]
@petermetz I have looked into the package cactus-cmd-api-server about the parameters to see if it is mentioned there on other files and for possible documentations. I have cleaned those that are not inside the other packages:
Screenshot 2022-05-11 133400 (changes 1)
Screenshot 2022-05-11 133418 (changes 2 and 3 whitepaper)

I have also ran npm run configure and npm run start:api-server command and it outputs a success
Screenshot 2022-05-11 133815 (npm run configure)
Screenshot 2022-05-11 133931 (npm run start api-server)

I would like to inquire if this is good to push for a PR or is there other specific documentation file I should update? Thank you

**Comment by ruzell22** [comment]
Remove ENV CACTUS_NODE_ID and CONSORTIUM_ID in dockerfile under cactus-cmd-api-server package, KEYCHAIN_SUFFIX_KEY_PAIR_PEM was not mentioned in the docker file so there is none in the file changes in dockerfile.
npm run configure and npm run start:api-server command were also successful after the changes.
Screenshot 2022-05-12 172129 (npm run configure)
Screenshot 2022-05-12 172213 (npm run start api-server)

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 I'm seeing the variable names in free text search popping up several times throughout the code-base still.

**Comment by ruzell22** [comment]
@petermetz I have removed more cactusNodeId, consortiumId, and keychainSuffixKeyPairPem and their ENV equivalent (excluding in example-config.json file which causes GitGuardian bot error during checks here).

**Review by petermetz — CHANGES_REQUESTED** [review]
> @petermetz I have removed more cactusNodeId, consortiumId, and keychainSuffixKeyPairPem and their ENV equivalent (excluding in example-config.json file which causes GitGuardian bot error during checks here).  

@ruzell22 If changing `example-config.json` trips the GitGuardian check we need to configure it to ignore that file because the alternative would be to not change that file ever again which is not feasable. Ignoring it in gitguardian should be safe because it's an example file with randomly generated keys in it.

**Comment by jagpreetsinghsasan** [comment]
@ruzell22 any updates on this PR? (If you think the necessary changes were done, you can always re-request for review)

**Comment by ruzell22** [comment]
Hello @petermetz , I have pushed the changes for the clean up so the new gitguardian workflow will be able to scan it. It passed. However, when I looked into more details about it, the scanner is still saying "Invalid token header. No credentials provided". It seems that even after being merged to the main repository, the workflow still doesn't have the permission to access the environmental secrets variable. I would like to ask assistance in that matter. Thank you. Below are the screenshots of the details.
image
image

**Comment by petermetz** [comment]
> Hello @petermetz , I have pushed the changes for the clean up so the new gitguardian workflow will be able to scan it. It passed. However, when I looked into more details about it, the scanner is still saying "Invalid token header. No credentials provided". It seems that even after being merged to the main repository, the workflow still doesn't have the permission to access the environmental secrets variable. I would like to ask assistance in that matter. Thank you. Below are the screenshots of the details. image image

@ruzell22 That's unfortunate. Please re-open the issue for the git guardian check, link to the comment you just made in a comment on *that* issue so that everyone has the context.
Then start a new PR to fix the issue that you re-opened.
Make sure to mark this PR dependent on that issue that you reopened for fixing the git guardian checks. That way if someone comes and looks at this they'll know exactly what happened and why is this PR stalling for now.

**Comment by ruzell22** [comment]
Hello @petermetz , I have done the ticket and PR for fixing the gitguardian. I have dropped some DMs for the possible solution that I have found for the environmental secrets variable. Thank you

**Comment by ruzell22** [comment]
Hello @petermetz , with gitguardian being removed, this PR is considered done and can be closed. Thank you.

**Review by petermetz — CHANGES_REQUESTED** [review]
@ruzell22 Please 
1. rebase onto upstream/main
2. Retest and see if this part of the commit message is still true: `"Parameter keyPairPem cannot be removed as it results to an error in running
the api server."`
2.1. Post the full error logs if it is still crashing or remove it otherwise.

**Review by petermetz — APPROVED** [review]
Thank you @ruzzel22, LGTM

**Review by sandeepnRES — APPROVED** [review]

**Pull request merged**
