### PR TITLE
test(connector-besu): migrate to jest for v21-get-block-test.ts

### PR DESCRIPTION
**Pull request by petermetz**
1. Also added a couple of extra assertions to make the test more robust.

[skip ci]

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by outSH** [comment]
LGTM

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
The CI on this one seems to be stuck permanently and GitHub tech support's recommendation for these type of situations is to close the PR and re-open it and see if that fixes it.

**Comment by petermetz** [comment]
Close+re-open did not make a difference so I'll have to recreate the PR from scratch with the same diff. Apologies everyone, especially those who reviewed it. Unfortunately this is the only option at this point according to the advice I've received from GitHub tech support.

**Pull request merged**
