### PR TITLE
build(connector-stellar): add a deploy contract endpoint

### PR DESCRIPTION
**Pull request by fazzatti**
- Add a Stellar Connector plugin following the same pattern as the **Besu Connector plugin**.
 - Add a deploy contract endpoint to the Stellar Connector plugin.

**Initialization remarks:**
Supports a network configuration object to define all integration services that seamlessly integrate with the Stellar test ledger within the Cacti test tooling. 

**Deploy remarks:**
The deploy process supports both the compiled smart contract WASM as well as the on-chain WASM hash as inputs. This follows the smart contract deployment design on Soroban(Stellar's smart contract platform). Refer to the [Stellar documentation](https://developers.stellar.org/docs/learn/fundamentals/stellar-data-structures/contracts) for further detail on this process.

More details can be found in the `README.md` file under the connector root directory.

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by fazzatti** [comment]
> @fazzatti Initial feedback before I do a detailed review:
> 
> 1. please fix the DCO
> 2. include a CI job (ci.yaml) to execute the test(s)
> 3. include all the information in the commit message not just the pull request description.

Thank you @petermetz !

>  1. please fix the DCO
I think I've got it right now. I didn't notice it was required to have the written line in the commit directly.

> 2. include a CI job (ci.yaml) to execute the test(s)
Just as opened the PR for review I thought 'perhaps the CI could've been changed in this change...'. Just did this now and I tried to follow the other examples here. Hope it is within the standard for the CI.

>3. include all the information in the commit message not just the pull request description.
Here I added additional bits when writing the PR and didn't think of going back to add those into the commit too but now I think I did update it correctly!

Thanks for the remarks! I appreciate!

**Review by outSH — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@fazzatti You need to add the `plugin-ledger-connector-stellar-changed` filter to the outputs of the job as well, not just declare it as a filter. Otherwise it won't be accessible to the other job's `if` condition and will always evaluate to false ending up skipping the job.

The outputs are at the top of the job declaration and look like this (and the stellar one is missing)

```yaml
  compute_changed_packages:
    outputs:
      cmd-api-server-changed: ${{ steps.changes.outputs.cmd-api-server-changed }}
      plugin-ledger-connector-polkadot-changed: ${{ steps.changes.outputs.plugin-ledger-connector-polkadot-changed }}
      plugin-ledger-connector-aries-changed: ${{ steps.changes.outputs.plugin-ledger-connector-aries-changed }}
      plugin-ledger-connector-besu-changed: ${{ steps.changes.outputs.plugin-ledger-connector-besu-changed }}
      plugin-ledger-connector-corda-changed: ${{ steps.changes.outputs.plugin-ledger-connector-corda-changed }}
      plugin-ledger-connector-fabric-changed: ${{ steps.changes.outputs.plugin-ledger-connector-fabric-changed }}
      plugin-ledger-connector-ethereum-changed: ${{ steps.changes.outputs.plugin-ledger-connector-ethereum-changed }}
      plugin-ledger-connector-iroha2-changed: ${{ steps.changes.outputs.plugin-ledger-connector-iroha2-changed }}
      plugin-ledger-connector-quorum-changed: ${{ steps.changes.outputs.plugin-ledger-connector-quorum-changed }}
      plugin-htlc-coordinator-besu-changed: ${{ steps.changes.outputs.plugin-htlc-coordinator-besu-changed }}
      test-tooling-changed: ${{ steps.changes.outputs.test-tooling-changed }}
      ghcr-corda-all-in-one-obligation-changed: ${{ steps.changes.outputs.ghcr-corda-all-in-one-obligation-changed }}
      ghcr-corda-all-in-one-changed: ${{ steps.changes.outputs.ghcr-corda-all-in-one-changed }}
      ghcr-dev-container-vscode-changed: ${{ steps.changes.outputs.ghcr-dev-container-vscode-changed }}

```

**Comment by fazzatti** [comment]
> @fazzatti You need to add the `plugin-ledger-connector-stellar-changed` filter to the outputs of the job as well, not just declare it as a filter. Otherwise it won't be accessible to the other job's `if` condition and will always evaluate to false ending up skipping the job.
> 
> The outputs are at the top of the job declaration and look like this (and the stellar one is missing)
> 
> ```yaml
>   compute_changed_packages:
>     outputs:
>       cmd-api-server-changed: ${{ steps.changes.outputs.cmd-api-server-changed }}
>       plugin-ledger-connector-polkadot-changed: ${{ steps.changes.outputs.plugin-ledger-connector-polkadot-changed }}
>       plugin-ledger-connector-aries-changed: ${{ steps.changes.outputs.plugin-ledger-connector-aries-changed }}
>       plugin-ledger-connector-besu-changed: ${{ steps.changes.outputs.plugin-ledger-connector-besu-changed }}
>       plugin-ledger-connector-corda-changed: ${{ steps.changes.outputs.plugin-ledger-connector-corda-changed }}
>       plugin-ledger-connector-fabric-changed: ${{ steps.changes.outputs.plugin-ledger-connector-fabric-changed }}
>       plugin-ledger-connector-ethereum-changed: ${{ steps.changes.outputs.plugin-ledger-connector-ethereum-changed }}
>       plugin-ledger-connector-iroha2-changed: ${{ steps.changes.outputs.plugin-ledger-connector-iroha2-changed }}
>       plugin-ledger-connector-quorum-changed: ${{ steps.changes.outputs.plugin-ledger-connector-quorum-changed }}
>       plugin-htlc-coordinator-besu-changed: ${{ steps.changes.outputs.plugin-htlc-coordinator-besu-changed }}
>       test-tooling-changed: ${{ steps.changes.outputs.test-tooling-changed }}
>       ghcr-corda-all-in-one-obligation-changed: ${{ steps.changes.outputs.ghcr-corda-all-in-one-obligation-changed }}
>       ghcr-corda-all-in-one-changed: ${{ steps.changes.outputs.ghcr-corda-all-in-one-changed }}
>       ghcr-dev-container-vscode-changed: ${{ steps.changes.outputs.ghcr-dev-container-vscode-changed }}
> ```

Thank you so much @petermetz !
It seems to be exactly it! I made the adjustments and as the CI is running right now, I can see the `Cactus_CI / cpl-connector-stellar` was executed and finished successfully!

**Comment by fazzatti** [comment]
@petermetz Just noticed that something else failed at the `Cactus_CI / yarn_custom_checks`  this time. I'll have a look at it!

**Comment by fazzatti** [comment]
> @petermetz Just noticed that something else failed at the `Cactus_CI / yarn_custom_checks` this time. I'll have a look at it!
 
 I think it should be ok now!

**Review by petermetz — APPROVED** [review]
@fazzatti You are most welcome, I'm glad we figured it out! Looking good now!

**Pull request merged**
