### PR TITLE
Merge Weaver codebase to Cacti

### PR DESCRIPTION
**Pull request by ryjones**

### CODE REVIEW

**Review by sanvenDev — APPROVED** [review]

**Comment by RafaelAPB** [comment]
This is big! 🚀

**Review by petermetz — APPROVED** [review]
Yay, thank you everyone and sorry I couldn't attend the merge (party) meeting!

Note to self: Double check that the main branch's linear git history is preserved (or restored somehow if it was lost due to this merge operation (which we never do out of convention unless it was rebased first)

**Comment by ryjones** [comment]
@petermetz do you want me to merge this?

**Comment by VRamakrishna** [comment]
@ryjones I think it'd be better if we abandoned this PR and instead opened a new one using the latest version of Weaver. This includes changes that address the issue identified in the HackerOne report, and also contain terminology fixes (avoiding terms like `master`, `whitelist`, etc.)

Which means we'll have to repeat the process we were attempting last week, but at least it'll be more streamlined, as we know what to expect. We are just waiting for @petermetz to confirm when he is available so we can schedule a call.

**Pull request closed without merging**
