### PR TITLE
fix(supply-chain-app): print correct web host in the cli-logs

### PR DESCRIPTION
**Pull request by deepto98**
Through this PR, I'm trying to fix the incorrect Cockpit address in CLI logs issue(https://github.com/hyperledger/cacti/issues/2390). This partially achieves it. In the [examples/supply-chain-app/README.md doc](https://github.com/hyperledger/cacti/blob/main/examples/supply-chain-app/README.md) there's two ways to build the supply chain app locally - 1. to build the entire app locally (under Running the Example Application Locally) 2. To build it using the dockerfile (under Building and running the container locally). The changes I've made in examples/cactus-example-supply-chain-backend/src/main/typescript/supply-chain-app.ts, changes the address to 127.0.0.1 and prints the same in the logs, but only if I build the entire app locally using method 1.
I also made changes in the Dockerfile and process.env, assuming the same output for the docker build. But somehow when I build the container locally using 2, I still get 0.0.0.0 in the output. I would need some help to further debug this issue.
(I'd made another PR with some errors, and have closed it)
Fixes https://github.com/hyperledger/cacti/issues/2390
Signed-off-by: deepto98 [ddepp98@outlook.com](mailto:ddepp98@outlook.com)

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@deepto98 This changes the host(s) that are being listened on, not what gets printed in the logs. Please only change what the logs are printing otherwise you'll introduce new issues such as only listening on the localhost of the container which then won't be accessible from the host machine at all.

**Comment by deepto98** [comment]
@petermetz Ah, I see, I'll make the change

**Comment by petermetz** [comment]
> @petermetz Ah, I see, I'll make the change

@deepto98 Thank you very much!

**Comment by petermetz** [comment]
@deepto98 Are you still working on this?

**Comment by petermetz** [comment]
Closing due to inactivity.

**Pull request closed without merging**
