### PR TITLE
docs(faq): add tutorial showing how to re-run a single CI workflow job

### PR DESCRIPTION
**Pull request by petermetz**
1. This is something that will come in handy as a reference material
while advising people on how to save on continuous integration
resources (which are precious)
2. Refactored the table of contents to be auto-generated by the VSCode
extension "Markdown All-in-One" so this way we don't have to keep it
up to date manually.
3. Also replaced mentions of "Cactus" with "Cacti" in a couple of the
older FAQ entries.

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by outSH — CHANGES_REQUESTED** [review]
- Please add this new entry to table of contents at the top of this page.
- (optionally) I'd also highlight that the refresh button next to search bar can be used as well

**Review by RafaelAPB — APPROVED** [review]

**Comment by petermetz** [comment]
> * Please add this new entry to table of contents at the top of this page.
> 
>     * (optionally) I'd also highlight that the refresh button next to search bar can be used as well

@outSH Thank you for the suggestions, I've applied the changes for both of those points!

**Review by sandeepnRES — APPROVED** [review]

**Pull request merged**
