### PR TITLE
chore(docs): generate browsable openapi specs

### PR DESCRIPTION
**Pull request by jenniferlianne**
Create project documentation reference page of all open api specs produced by monorepo projects.

## Commit to be reviewed

chore(docs): generate browsable openapi specs 

    Primary Changes
    1. Updated deploy_docs workflow to generate markdown for openapi
        specs files present across packages
    
    Secondary Changes required to incorporate 1)
    2. Added docs/scripts/publish_openapi.py to generate markdown 
    3. Added swagger-ui-tag plugin to mkdocs
    4. Updated docs/requirements.txt for the above plugin to be
       downloaded.

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by sandeepnRES — APPROVED** [review]

**Review by outSH — APPROVED** [review]

**Review by petermetz — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@jenniferlianne One quick change request:
Please fix the action linter error:

```sh


Check failure on line 18 in .github/workflows/deploy_docs.yml
GitHub Actions / ActionLint / Lint_GitHub_Actions

expected "inputs" key for "workflow_dispatch" section but got "branches"
```

It looks like the discussion here has more context on what's going wrong with it, but I haven't done an in-depth analysis.
https://github.com/actions/runner/issues/1858

**Review by petermetz — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@jenniferlianne Sorry, one last nit-pick:

Commits that have the type of `feat` will appear in the release notes (later when we cut the release) as production code feature additions.

The important thing is that the release notes that we  generated from the commit messages will provide a useful source of information to the reader.

For example there is a docs commit type defined in the standard of conventional commits that should be used to mark all documentation related changes, be that tooling of the documentation or the actual content of the documentation.

- Therefore, please rewrite the commit message based on the guide below.
- Please also make sure to sync the commit message with the pull request description.
- Please also make sure to sync the commit subject line (the first line) with the pull request title.

# Guide to Writing Good Commit Messages with Conventional Commits

Commit messages are an essential part of maintaining a project's history. Good commit messages help team members understand the context and purpose of changes. The Conventional Commits specification provides a standard for commit messages that makes this process more efficient and consistent.
Conventional Commits Format

The Conventional Commits specification outlines a format for commit messages that is structured and informative. Here is the basic format:

```sh
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

## Components of a Commit Message

1. Type: A keyword indicating the type of change.
2. Scope: A noun describing the section of the codebase affected (optional but recommended).
3. Description: A brief summary of the change.
4. Body: A more detailed explanation of the change (optional).
5. Footer(s): Information about breaking changes or issues this commit closes (optional).

## Common Types

- feat: A new feature for the user.
- fix: A bug fix (reserved for production bug-fixes only).
- docs: Documentation changes.
- style: Code style changes (e.g., formatting, missing semicolons).
- refactor: Code changes that neither fix a bug nor add a feature.
- perf: Changes that improve performance.
- test: Adding or correcting tests.
- chore: Changes to the build process or auxiliary tools and libraries such as documentation generation.

## Example Commit Messages

Adding a New Feature

```sh
feat(parser): add ability to parse arrays
```

### Fixing a Bug

```sh
fix(api): ensure correct response format
```

### Updating Documentation

```sh
docs(readme): update installation instructions
```

### Style Changes

```sh
style(button): remove unnecessary margin
```

### Code Refactoring

```sh
refactor(user-service): extract user validation logic
```

### Performance Improvement

```sh
perf(database): optimize query performance
```


### Adding Tests

```sh
test(auth): add unit tests for login functionality
```

### Miscellaneous Chores

```sh
chore(deps): update dependency versions
```

## Special Considerations for fix

**Reserved for Production Bug-Fixes**

The fix type should only be used for production bug fixes. If you're correcting or repairing documentation, tutorials, examples, or test cases, do not use fix. Instead, use docs for documentation, test for test cases, and chore for other non-code changes.

### Examples of Incorrect Usage of fix

Incorrect

```sh
fix(readme): correct spelling mistake
```

Correct

```sh
docs(readme): correct spelling mistake
```

Incorrect

```sh
fix(test): repair broken test case
```

Correct

```sh
test(unit): repair broken test case
```

Writing a Good Commit Message

1. **Be Descriptive**: Your commit message should clearly describe what the change does.
2. **Keep it Short and Sweet**: The first line should be 72 characters or less. The body, if needed, should be wrapped at a maximum 80 characters (the commit linter will fail if any line is longer than 100 characters).
3. **Use the Imperative Mood**: Start the message with a verb (e.g., "add," "fix," "remove").
4. **Use Proper Punctuation**: Lowercase the first letter of the type and the description, and do not end the description with a period.

### Example Commit Message with Body and Footer

```sh
feat(auth): add OAuth2 authentication

This adds OAuth2 authentication to the user service, allowing users
to log in with their Google account.

BREAKING CHANGE: The login endpoint now requires a different payload.

Closes #123

```


By following these guidelines, you ensure that your commit messages are clear, consistent, and useful for anyone who might read them in the future.

Following the Conventional Commits specification helps in creating a well-maintained and understandable project history, which can significantly improve collaboration and productivity in software development.

**Comment by jagpreetsinghsasan** [comment]
Hi @jenniferlianne 
I have updated the PR title and message and now all that is needed is to squash merge the commits into one single commit with the commit title and body to match the PR description, i.e.,
image
Rest looks good to me

**Review by petermetz — CHANGES_REQUESTED** [review]
@jenniferlianne One last nit: Please squash the commits together into a single one.

**Review by petermetz — APPROVED** [review]

**Pull request merged**
