### PR TITLE
refactor: rename OpenAPI extension x-hyperledger-cactus

### LINKED ISSUE #2689: refactor: rename OpenAPI extension x-hyperledger-cactus
### Description

Rename the extension in the OpenAPI spec json files from `x-hyperledger-cactus` to `x-hyperledger-cacti` to match the project rename.

**This is a breaking change.**

### Acceptance Criteria
1. Tests are passing
2. Example supply chain app still works (ran locally with the latest codebase)

### PR DESCRIPTION
**Pull request by aldousalvarez**
### **Commit** to be reviewed
---
refactor: rename OpenAPI extension x-hyperledger-cactus
```
Primary Changes
----------------
1. Updated openapi.yaml in connector-corda to match
   the project rename x-hyperledger-cacti
```

Fixes #2689

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by jagpreetsinghsasan** [comment]
@aldousalvarez please fix the PR and the commit message to the standard one I have mentioned several times.

**Review by outSH — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@aldousalvarez https://github.com/hyperledger/cacti/issues/2689 is about renaming them in the .json files. This PR is renaming it in the .yaml one which is generated from the .json one.

Once you rename it in the .json files the .yaml file should update automatically.

**Comment by aldousalvarez** [comment]
@petermetz the .json file is already updated with the correct one which is x-hyperledger-cacti, when I tried to clean and configure it does not update automatically so I just updated the .yaml manually

**Comment by petermetz** [comment]
@aldousalvarez 

> the .json file is already updated with the correct one

In that case https://github.com/hyperledger/cacti/issues/2689 was already completed, no need for this PR.

> when I tried to clean and configure it does not update automatically so I just updated the .yaml manually

Let's uncover the reason why it's not getting updated. Could you please investigate why is that?
Once the code generation bug is fixed the yaml in this PR will automatically get updated and we don't need to worry about the diff in here (changing the yaml file manually)

**Comment by aldousalvarez** [comment]
@petermetz okay will dol investigate on this one and will let you know as soon as possible if I have found what is causing this issue and how to fix this as well

**Comment by aldousalvarez** [comment]
Hello @petermetz should I create a new PR or will you reopen this PR and its Issue because I have changes in cactus-plugin-ledger-connector-polkadot that needs to rename the openapi extension to x-hyperledger-cacti

And also regarding the removal of the openapi.yaml in cactus-plugin-ledger-connector-corda should I create also a separate PR and issue or should I just include it here and just explain why we are removing it

**Pull request closed without merging**
