### PR TITLE
test(weaver-fabric-examples): use docker compose v2

### PR DESCRIPTION
**Pull request by jenniferlianne**
Updates the weaver fabric example network.sh file to use docker compose v2 syntax.  docker-compose
v1 will be dropped on the github runners in a few weeks. (ref: https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md)

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@jenniferlianne LGTM, thank you very much for the contribution!

**Comment by VRamakrishna** [comment]
@jenniferlianne I just triggered various CI actions that were not automatically run when you submitted the PR. If the tests pass, I'll approve this.

But note that `docker-compose` is employed in several different Weaver modules (see subfolders within `core` and `samples` for examples), and not just the test networks, so we should be doing this upgrade everywhere. Would you prefer to fix all of them in this PR itself or should we merge this and do the rest in a subsequent PR?

**Comment by jenniferlianne** [comment]
@VRamakrishna Thanks.  Could you please put this one through?  I have another change pending which updates network.sh to use the Fabric versions specified in the makefile that I'd like to put in.

Reading the contribution guide, I thought I would separate the small-ish change into two very small ones to make the intention clear.  Not sure if this was a good choice.

**Comment by VRamakrishna** [comment]
@jenniferlianne Here is a list of other locations within the `weaver` folder where `docker-compose` is being used:
- https://github.com/hyperledger/cacti/tree/main/weaver/core/drivers/fabric-driver
- https://github.com/hyperledger/cacti/tree/main/weaver/core/drivers/corda-driver
- https://github.com/hyperledger/cacti/tree/main/weaver/core/relay
- https://github.com/hyperledger/cacti/tree/main/weaver/core/identity-management/iin-agent
- https://github.com/hyperledger/cacti/tree/main/weaver/tests/network-setups/indy/docker
- https://github.com/hyperledger/cacti/tree/main/weaver/tests/network-setups/corda

In some locations, the `docker-compose` commands are in the makefiles, and in others, in scripts. You may have to do a find (or a find-and-replace) within the above folders.

**Comment by jenniferlianne** [comment]
Closing, will resubmit with broader changes as requested.

**Pull request closed without merging**
