### PR TITLE
ci(github): loosen up file matching when selecting tests to run

### PR DESCRIPTION
**Pull request by outSH**
- Current file match glob is incorrect and never matches a file.
- I didn't find a way to filter files by extension (as it was attempted now) so I propose to loose up the rules and run the test if any file in a package has changed.

## More context
- I've noticed in another PR (https://github.com/hyperledger/cacti/pull/3018) that most tests didn't run, even though this PR changes most ts files, from all packages I think.
- I've digged a little bit in dorny/paths-filter sources, found out the file matching string is passed to `picomatch` for actual filtering.
- `picomatch` is very simple (but fast), and does not support any advanced globbing techniques. I've done some tests locally, and the best solution I found is to use less strict matching rules.

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by sandeepnRES** [comment]
Hi @outSH, I didn't get what you mean by `never matches a file`.
What I saw on PRs was, if there was a code change, the corresponding CI was running else it skipped.

**Comment by outSH** [comment]
> Hi @outSH, I didn't get what you mean by `never matches a file`. What I saw on PRs was, if there was a code change, the corresponding CI was running else it skipped.

@sandeepnRES 
Yeah, I've changed the original PR so it may not be clear, sorry. I've opened another one on my fork to make it more persitent here - https://github.com/outSH/cactus/pull/11. As you can seet his PR changes all packages, but none are marked as changed by the CI:

image

This is because of invalid glob in config as I described above

**Comment by outSH** [comment]
@petermetz The problem was spotted on PR opened here, you can see this happening here - https://github.com/hyperledger/cacti/pull/3018

**Review by sandeepnRES — APPROVED** [review]
LGTM

**Review by petermetz — COMMENTED** [review]
@outSH My theory right now is that this won't fix the issue because of the underlying cause explained here: https://github.com/hyperledger/cacti/pull/3018#issuecomment-1957355218

Is there any chance that you verify it over there on that PR?
I'm thinking that if my research is correct than we don't need this PR at all.

**Review by petermetz — APPROVED** [review]
@outSH LGTM - later once the path-filter action has the ability to support our more fine-grained filtering use-case I'll recommend to change the glob patterns once again, but in the meantime this is definitely a net positive! Thank you very much for taking the time to send this in!

**Pull request merged**
