### PR TITLE
build(deps): bulk fix CVEs via dependency resolution overrides 2023-10-23

### LINKED ISSUE #2544: build(plugin-ledger-connector-ubiquity): stop using GitHub URL as client version
We need to get rid of this dependency declaration that depends on a GitHub URL:
`"@ubiquity/ubiquity-ts-client-modified": "https://github.com/RafaelAPB/ubiquity-ts-client-mirror.git",`
because it is technical debt and a security concern at the same time.

The package in question: `packages/cactus-plugin-ledger-connector-ubiquity/package.json``
Gitlab repo: https://gitlab.com/Blockdaemon/ubiquity/ubiquity-ts-client/-/releases

- Plan A: Have the maintainers of this package publish an up to date & working
version to npmjs.com so that we can use it from there.
- Plan B: If they publish it to an alternative registry that's fine too we just
need to create the mapping for the scope (as long as they do have an org scope)
- Plan C: Their website appears to have a much newer version of the OpenAPI specification
for their APIs (v3.0.0). As a plan C we could even just generate our own client
and use that as part of the connector. This is not desired because then we would
have to maintain code that we don't really control (we don't write the specs
nor we develop the back-end APIs that they must comply with) but as a last 
resort it is an acceptable solutin if all else had failed.

OpenAPI specs: https://ubiquity.docs.blockdaemon.com/

cc: @RafaelAPB

### LINKED ISSUE #2828: build(deps): bulk fix CVEs via dependency resolution overrides 2023-10-23
### Description

Upgrading vulnerable dependencies have become a game of whack-a-mole: Vulnerabilities that I've submitted pull requests for in the past few weeks are reappearing because new pull requests keep adding back the vulnerable versions of these dependencies to the project build. 
We could have a CI step scanning for these and block the PR's from getting merged but that's extra resources used on the already stretched-thin CI so the simpler route is to start using the central (root package.json file's) resolution overrides more aggressively. Previously I was advocating for this to be a last resort, but seeing in recent weeks how the accidental re-adding of vulnerabilities happen very frequently nowadays (due to project growth which is a good thing in itself) I changed my mind on it and decided that my new recommendation is to lock ourselves away from vulnerable versions of dependencies entirely via the centralized overrides. 

The scope of this task: Submit one PR with resolution overrides.

### Acceptance Criteria
1. All the resolution overrides are defined with a "great or equal" qualifier to ensure that we are not blocking people from upgrading further (e.g., if v0.9.0 is vulnerable, we should say `>=1.0.0` instead of `=1.0.0` because the former is not forcing us to not use v1.1.0 in the future as it comes out)
2. Each resolution override is detailed in the commit message body, links to the github security advisory and the CVE IDs are included
3. Build is still working
4. There is no significant slowdown in the build
5. The tests are passing as well

### PR DESCRIPTION
**Pull request by petermetz**
1. Couldn't get rid of vulnerable versions in a couple of dependencies
because the underlying dependencies have gone ESM only which is a blocker
for us at the moment unfortunately.
2. Swapped out the ubiquity TS client to a version of it that I self
published onto npm after a full renovation of all of its dependencies.

Depends on #2807 (because that one also has a couple of dependency bumps
that are needed to eliminate the vulnerabilities)

Fixes #2828
Fixes #2544

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by petermetz** [comment]
cc: @RafaelAPB (please see point 2)

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by izuru0 — APPROVED** [review]
LGTM

**Pull request merged**
