### PR TITLE
test(weaver): added missed fabric-ca-server config

### PR DESCRIPTION
**Pull request by sandeepnRES**
- These files were missed when we were merging Weaver into Cacti, due to a wrong `.gitignore`. It also extends expiry of certs to 10 years.

- test(weaver): re-generate expired fabric testnet certs

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

### CODE REVIEW

**Review by VRamakrishna — APPROVED** [review]

**Review by outSH — APPROVED** [review]

**Review by petermetz — APPROVED** [review]

**Review by petermetz — COMMENTED** [review]
@sandeepnRES A couple of them are still failing unfortunately :-(

Test Asset Exchange Fabric / asset-exchange-fabric-local (pull_request) Failing after 6m

Test Asset Transfer / asset-transfer-local (pull_request) Failing after 13m

**Comment by sandeepnRES** [comment]
> @sandeepnRES A couple of them are still failing unfortunately :-(
> 
> Test Asset Exchange Fabric / asset-exchange-fabric-local (pull_request) Failing after 6m
> 
> Test Asset Transfer / asset-transfer-local (pull_request) Failing after 13m

It seems the fabric certificates for test network have expired, will re-issue them in this PR only.

**Review by petermetz — CHANGES_REQUESTED** [review]
@sandeepnRES Please squash the commits together if possible

**Comment by sandeepnRES** [comment]
> @sandeepnRES Please squash the commits together if possible

Done.

**Review by petermetz — APPROVED** [review]
@sandeepnRES Thank you, LGTM!

**Pull request merged**
