### PR TITLE
chore(weaver): use docker compose v2

### PR DESCRIPTION
**Pull request by jenniferlianne**
`Primary change:  Updates the weaver files
to use docker compose v2 syntax.  docker-compose
v1 will be dropped on the github runners
shortly.`

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Comment by sandeepnRES** [comment]
Hi @jenniferlianne Can you update the version of docker compose in docs:
`docs/docs/weaver/getting-started/test-network`, in all the `setup-*.md` files, we have prerequisites defined where right now we say use version below 2 for docker-compose. Can you please update that?

**Comment by jenniferlianne** [comment]
@sandeepnRES  I have updated all 10 weaver doc .md files that make reference to the Docker Compose version.

**Review by petermetz — APPROVED** [review]

**Review by petermetz — COMMENTED** [review]
@jenniferlianne LGTM, thank you!

**Comment by VRamakrishna** [comment]
Just noting that this PR is a replacement for #3358.

**Review by VRamakrishna — CHANGES_REQUESTED** [review]
@jenniferlianne Please undo all changes within `weaver/docs/`. I've submitted another PR (to be merged today) where I delete that folder entirely as it was already deprecated (moved to the `docs` folder in the root) last year: https://github.com/hyperledger/cacti/pull/3358.

**Comment by jenniferlianne** [comment]
I have removed the changes to weaver/docs as requested by @VRamakrishna.

**Review by VRamakrishna — APPROVED** [review]

**Pull request merged**
