### PR TITLE
docs(readme): fix broken VS-code badge in the readme

### PR DESCRIPTION
**Pull request by legendarykamal**
Signed-off-by: Kamal Nayan <95926324+legendarykamal@users.noreply.github.com>

Solves #2169

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Review by jagpreetsinghsasan — CHANGES_REQUESTED** [review]
LGTM. Can you squash merge the commits into a single one?

**Comment by jagpreetsinghsasan** [comment]
> @jagpreetsinghsasan I don't think that would be possible unless I force push my branch , but it won't have any effect on the PR. So is it really needed ?

You can simply rebase and then reset on the the latest main branch commit. Then you can create a new commit out of this. And yes, its important to have a single commit with a proper commit message, to navigate through history of commits easily and proper management of code. 
Please refer to [our contributing guide](https://github.com/hyperledger/cactus/blob/main/CONTRIBUTING.md) for more information. You can also refer to various commits to have an idea of how the commit messages can be created, for example [this](https://github.com/hyperledger/cactus/pull/2159/commits/97d7ef24a7060a5aa1e60ff8341722fce63a39ec) one.

**Comment by legendarykamal** [comment]
allright thanks for confirming in @jagpreetsinghsasan ✔️

**Review by petermetz — CHANGES_REQUESTED** [review]
@legendarykamal Please use the shields.io link insted of badgen.
https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc

Also please fix the commit message and PR title to be compliant with the linter and squash+rebase onto upstream/main.

Thank you!

**Comment by petermetz** [comment]
Closing due to inactivity. Happy to re-open later if it's still relevant.

**Pull request closed without merging**
