### PR TITLE
feat(persistence-fabric): add sample setup scripts, improve documentation

### PR DESCRIPTION
**Pull request by outSH**
- Fix error when empty `transaction.actions` was received from a block.
- Copy schema SQL during build.
- Remove unique constraint on fabric transactions hash column (there are transactions with empty hash that would break it).
- Improve parsing of certificate subject/issuer attributes to handle more delimiters.
- Use new `install-fabric.sh` script (that is recommended for Fabric 2.5) instead of old bootstrap to fix some runtime issues that I've encountered.
- Add sample setup scripts. Simple can be used to run persistence against already running fabric ledger, complete will setup entire environment and run some basic operations to generate sample data.
- Improve documentation to include these new scripts and how to use them, fix smaller issues.

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you very much!

**Review by RafaelAPB — APPROVED** [review]
This is a great PR, thanks!
I like very much the fact the examples are layed down as a tutorial. However, perhaps the best organization is instead of having scripts on `test/manual`, to have instead an example package under /examples?
Rest LGTM

**Comment by outSH** [comment]
@RafaelAPB Thanks! I believe a similar idea was discussed before, but the challenges were:
- If `/examples` were not included in the CI build, it could lead to discrepancies between the examples and the actual code.
- If `/examples` were built as an actual package alongside other packages, it could quickly grow in complexity due to dependencies.

I opted for a `manual`  directory because I used a similar convention for other scripts. However, I'm open to adding /examples inside the persistence plugin folder if that would be clearer for users. :)

**Comment by petermetz** [comment]
I agree with both of you. Pros and cons to both approaches unfortunately and it's hard to tell which one has worse cons and/or better pros.

**Pull request merged**
