### PR TITLE
build(ubiquity): remove ubiquity connector plugin

### PR DESCRIPTION
**Pull request by RafaelAPB**
Currently, the Ubiquity package is not supported and it is breaking. Therefore, we shall remove it until support is provided.

Shall i also commit the updated yarn.lock?

### CODE REVIEW

**Comment by outSH** [comment]
> Shall i also commit the updated yarn.lock?

@RafaelAPB Yes, this is necessary to make CI pass

**Review by petermetz — APPROVED** [review]
LGTM - thank you for the quality of life improvements for every contributor! It inches us closer to a fully green CI :-)

**Comment by RafaelAPB** [comment]
@outSH @petermetz updated. Good to go? :)

**Review by petermetz — APPROVED** [review]
@RafaelAPB Sorry for missing the earlier question about the yarn.lock file!

Yes, you `must` commit the updated lock file otherwise the CI will not let it pass.

**Review by outSH — APPROVED** [review]

**Pull request merged**
