### PR TITLE
feat(fabric-connector): add getChainInfo, improve getBlock output

### PR DESCRIPTION
**Pull request by outSH**
- Add new method `getChainInfo` for quering chain information from qscc.
- Add `GetChainInfoEndpointV1` to allow calling `getChainInfo` remotely.
- Refactor `getBlock` so it can return same custom block formats as `WatchBlocks`. Default remains the same (full decode block). BREAKING CHANGE: It accepts `type` instead of `skipDecode` flag.
- Move common block formatting logic to `cacti-block-formatters.ts`.
- Add tests for new features. Move test common to quering `qscc` to single file to increase CI speed.

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@outSH LGTM, thank you!

**Comment by outSH** [comment]
As per @petermetz suggestion in https://github.com/hyperledger/cacti/pull/3308#discussion_r1637090342, I've rebased with main and changed the following:
- Added `openapi.tpl.json`, built `openapi.json` from it.
- Changed `FullBlockTransactionEventV1.type` to `transactionType`
- Changed `GetBlockRequestV1.type` -> `responseType`

**Comment by petermetz** [comment]
> As per @petermetz suggestion in [#3308 (comment)](https://github.com/hyperledger/cacti/pull/3308#discussion_r1637090342), I've rebased with main and changed the following:
> 
>     * Added `openapi.tpl.json`, built `openapi.json` from it.
> 
>     * Changed `FullBlockTransactionEventV1.type` to `transactionType`
> 
>     * Changed `GetBlockRequestV1.type` -> `responseType`

@outSH Thank you very much!

**Review by RafaelAPB — APPROVED** [review]
LGTM, nice work

**Pull request merged**
