### PR TITLE
test(cbdc-example): removed dependency on chai and update tests

### LINKED ISSUE #3034: bug(cbdc-example): the tests of the CBDC app are not running
**Describe the bug**

The tests of the CBDC app are failing due to a problem with the `chai` package.

**To Reproduce**

When running "npm run test" in `examples/cactus-example-cbdc-bridging-backend` an error is thrown.

**Expected behavior**

All tests passing.

**Logs/Stack traces**

```
> @hyperledger/cactus-example-cbdc-bridging-backend@2.0.0-alpha.2 test
> nyc cucumber-js --tags @besu ./src/test/typescript/cucumber/features/*.feature --require-module ts-node/register --require './src/test/typescript/cucumber/*/*.ts'

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/get-func-name/index.js from /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai/utils/inspect.js not supported.
Instead change the require of index.js in /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai/utils/inspect.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai/utils/inspect.js:4:15)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai/utils/objDisplay.js:11:15)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai/utils/getMessage.js:13:18)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai/utils/index.js:34:22)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/lib/chai.js:25:12)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/chai/index.js:1:18)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4)
    at Object.<anonymous> (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/src/test/typescript/cucumber/steps/besu-gateway.steps.ts:7:16)
    at m._compile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/ts-node/dist/index.js:327:29)
    at Module.replacementCompile (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:58:13)
    at /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/append-transform/index.js:62:4
    at require.extensions.<computed> [as .ts] (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/ts-node/dist/index.js:329:16)
    at /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/cucumber/lib/cli/index.js:142:42
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/cucumber/lib/cli/index.js:142:22)
    at /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/cucumber/lib/cli/index.js:169:41
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/cucumber/lib/cli/index.js:44:103)
    at _next (/home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend/node_modules/cucumber/lib/cli/index.js:46:194)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
npm ERR! Lifecycle script `test` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @hyperledger/cactus-example-cbdc-bridging-backend@2.0.0-alpha.2 
npm ERR!   at location: /home/andre_augusto/cacti/examples/cactus-example-cbdc-bridging-backend 
```

### PR DESCRIPTION
**Pull request by AndreAugusto11**
* Chai was removed as dependency of the cbdc-backend package
* A test scenario was removed in the 'bridge-back' feature due to having duplicated logic with another one in the same file
* Some tests were failing due to timeouts, so we added an explicit and generous timeout limit for each step

closes #3034

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@AndreAugusto11 `fix` means that something was fixed that would've been broken in production but this only touches the tests and the test dependencies.

The idea behind the above: People reading the release notes would get this on the list of bugs that were fixed but wouldn't really know what to make of it because it has no effect on their production deployments.

And therefore my request is to set the scope to `test` instead of `fix`

Looks good otherwise!

**Comment by AndreAugusto11** [comment]
@petermetz thanks a lot. I'm always in a struggle with the naming, but getting better!! 😀

**Comment by petermetz** [comment]
> @petermetz thanks a lot. I'm always in a struggle with the naming, but getting better!! 😀

@AndreAugusto11 No worries! It takes a long time (speaking from personal experience) to build up the muscle memory for these kind of things so until then the best course of action is to just keep working on it!

**Review by petermetz — APPROVED** [review]
LGTM

**Review by outSH — CHANGES_REQUESTED** [review]
@AndreAugusto11 Thanks, looks great, please update the `yarn.lock` file to fix the tests and we're good to go :) 

You could also pin the dependency versions in `cactus-example-cbdc-bridging-backend/package.json` (e.g. `"cucumber": "^5.0.3",` -> "5.0.3"). This _should_ be done in separate PR but since the change is so small I think it's OK to fix it "by the way" - completely optional :)

**Comment by AndreAugusto11** [comment]
@outSH thanks, also pinned all versions accordingly.

**Review by outSH — APPROVED** [review]

**Pull request merged**
