### PR TITLE
feat(test-tooling): add Stellar test ledger

### LINKED ISSUE #3239: test(stellar-test-ledger): Stellar Test Ledger
**Is your feature request related to a problem? Please describe.**
Implement a Test Ledger able to pull up a docker image with a stellar network core, validators, and necessary services(Horizon API, Soroban RPC, and Friendbot) to run Stellar-related Cacti tests against.

**Describe the solution you'd like**
The Stellar Test Ledger should:
- Start, stop, and destroy a docker container with the test ledger.
- Contains all the necessary services to execute complete use cases in Stellar.
  - Horizon API server for interacting with the Stellar network.
  - Soroban RPC for interacting with smart contracts.
  - Friendbot for starting and funding accounts in a test environment.
- Ensure all services are available before allowing the tests to be executed.
- Allow for an ephemeral pristine local ledger to be started with no history.

**Additional context**
This is the first step of the initiative mention in the issue https://github.com/hyperledger/cacti/issues/3238 .

### PR DESCRIPTION
**Pull request by fazzatti**
- Add a Stellar test ledger class that can be used in integration tests to start and stop a Stellar test network based on the Stellar quickstart docker image: https://github.com/stellar/quickstart

- Includes the following services for fetching ledger state, executing classic transactions and also soroban smart contracts transactions.
  - Stellar Core
  - Horizon API
  - Soroban RPC
  - Friendbot

Fixes #3239

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@fazzatti LGTM - thank you!

**Review by outSH — APPROVED** [review]
LGTM, thank you for your contribution

**Review by petermetz — APPROVED** [review]
@fazzatti Looking good now, thank you!

**Review by petermetz — CHANGES_REQUESTED** [review]
@fazzatti We are almost there! Now it's just the linter complaining:

```sh
43s
Run yarn lint
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/resource-limits.ts:2:38 - Unknown word (Soroban)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/resource-limits.ts:[1](https://github.com/hyperledger/cacti/actions/runs/9185073647/job/25258422445?pr=3274#step:6:1)1:75 - Unknown word (configfured)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:39:38 - Unknown word (soroban)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:68:77 - Unknown word (soroban)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:210:11 - Unknown word (cmds)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:2[14](https://github.com/hyperledger/cacti/actions/runs/9185073647/job/25258422445?pr=3274#step:6:15):9 - Unknown word (cmds)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:217:9 - Unknown word (cmds)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:221:9 - Unknown word (cmds)
/home/runner/work/cacti/cacti/packages/cactus-test-tooling/src/main/typescript/stellar/stellar-test-ledger.ts:227:9 - Unknown word (cmds)
CSpell: Files checked: 1105, Issues found: 9 in 2 files
Error: Process completed with exit code 1.
```

You can also run this check locally by saying `yarn lint` on the terminal.

**Review by petermetz — APPROVED** [review]
@fazzatti Yup, we are looking very good! Thank you for the updates and the explanation on what the fix was! LGTM

**Comment by RafaelAPB** [comment]
A bit late to the game, but came here to thank you @fazzatti ! Great contribution!

**Pull request merged**
