### PR TITLE
feat(cactus-example-discounted-asset-trade): use openapi ethereum connector

### PR DESCRIPTION
**Pull request by outSH**
- Refactor discounted asset trade sample to use openapi ethereum connector
    instead of ethereum-socketio.
- Use eth signing utils from ethereum connector package.
- Fix nodejs setup in indy-sdk-cli docker image.
- Small fixes after recent ethereum connector refactors.

Depends on: #2645

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

### CODE REVIEW

**Review by petermetz — COMMENTED** [review]
@outSH There's only one parent PR but 4 commits. Does this need a rebase + squash?
The one commit that matches the PR title is looking good otherwise.

**Comment by outSH** [comment]
> @outSH There's only one parent PR but 4 commits. Does this need a rebase + squash? The one commit that matches the PR title is looking good otherwise.

@petermetz These are commits from dependencies of the dependency

**Review by izuru0 — APPROVED** [review]
LGTM

**Comment by petermetz** [comment]
> > @outSH There's only one parent PR but 4 commits. Does this need a rebase + squash? The one commit that matches the PR title is looking good otherwise.
> 
> @petermetz These are commits from dependencies of the dependency

@outSH /facepalm - sorry, I should've known/checked/etc.

**Review by petermetz — CHANGES_REQUESTED** [review]
@outSH Looks good but please pass it back for review once the parent PR(s) have been merged and the conflicts have been resolved! (I'm just marking it down as a change request to not forget that I have to take a second pass on it once it reached it's final state)

**Comment by outSH** [comment]
> pass it back for review once the parent PR(s) have been merged and the conflicts have been resolved

Done, I've also included the following changes:
- Use eth signing utils from ethereum connector package.
- Fix nodejs setup in indy-sdk-cli docker image.
- Small fixes after recent ethereum connector refactors.

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
> > pass it back for review once the parent PR(s) have been merged and the conflicts have been resolved
> 
> @petermetz Done, I've also included the following changes:
> 
>     * Use eth signing utils from ethereum connector package.
> 
>     * Fix nodejs setup in indy-sdk-cli docker image.
> 
>     * Small fixes after recent ethereum connector refactors.

@outSH Gotcha, LGTM, thank you for the updates!

**Pull request merged**
