### PR TITLE
feat(besu-test-ledger): send funds to already created address

### LINKED ISSUE #2250: feat(besu-test-ledger): enable sending funds to already created account
**Is your feature request related to a problem? Please describe.**
Currently, the implementation of `createEthTestAccount` includes the creation of an account and sends some funds to get things started. It would be important to separate this function in two, in a way that it is possible to send funds to an already created account.

**Describe the solution you'd like**
Create function `sendEthToAccount` and call it from `createEthTestAccount`. If an address already exists we would only need to call the first method.

### PR DESCRIPTION
**Pull request by AndreAugusto11**
Enable sending funds to an existing account.

New method created:
* sendEthToAccount

closes #2250

Signed-off-by: André Augusto <andre.augusto@tecnico.ulisboa.pt>

### CODE REVIEW

**Comment by AndreAugusto11** [comment]
FYI @RafaelAPB @petermetz the `cactus-plugin-connector-ubiquity` is failing the CI [here](https://github.com/hyperledger/cactus/actions/runs/3868745828/jobs/6594547529#step:6:2378)

**Review by jagpreetsinghsasan — APPROVED** [review]

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@AndreAugusto11 LGTM but please fix the test(s) that started failing:

[2023-01-31_205215_cacti_ci_besu_connector_crash.log](https://github.com/hyperledger/cactus/files/10551219/2023-01-31_205215_cacti_ci_besu_connector_crash.log)

**Comment by petermetz** [comment]
> @petermetz as @AndreAugusto11 said, the ubiquity connector tests fail, because this workspace does not have an api key for that connector. Tests only run successfully on my repo. Given this, shall we remove the ubiquity connector tests from the CI?

@RafaelAPB I'd rather just "power through it" as-in, fix the failing tests as soon as possible instead of removing them. Seeing the tests fail on every PR (pointlessly) is annoying (to me at least) but this way it is a constant reminder that we should really fix them... :-)

**Comment by AndreAugusto11** [comment]
> @AndreAugusto11 LGTM but please fix the test(s) that started failing:
> 
> [2023-01-31_205215_cacti_ci_besu_connector_crash.log](https://github.com/hyperledger/cactus/files/10551219/2023-01-31_205215_cacti_ci_besu_connector_crash.log)

@petermetz I am able to run the failing tests related to Besu, locally (`Cactus_CI / cactus-test-plugin-ledger-connector-besu` and `Cactus_CI / cactus-plugin-ledger-connector-besu`), could you confirm this is an issue caused by this code pls?

[get-balance-endpoint.test.ts.log](https://github.com/hyperledger/cacti/files/10695551/get-balance-endpoint.test.ts.log)
[openapi-validation.test.ts.log](https://github.com/hyperledger/cacti/files/10695552/openapi-validation.test.ts.log)

**Comment by RafaelAPB** [comment]
> 

The tests are failing because we are not giving them a valid API key for Ubiquity. Is the solution you to generate one and put it on the env vars of the project?

**Comment by petermetz** [comment]
> @petermetz
> 
> The tests are failing because we are not giving them a valid API key for Ubiquity. Is the solution you to generate one and put it on the env vars of the project?

@RafaelAPB @AndreAugusto11 Sorry, I forgot about that. We need to fix it somehow but not in scope for this PR so nvm on that topic for here.

**Comment by petermetz** [comment]
> > @AndreAugusto11 LGTM but please fix the test(s) that started failing:
> > [2023-01-31_205215_cacti_ci_besu_connector_crash.log](https://github.com/hyperledger/cactus/files/10551219/2023-01-31_205215_cacti_ci_besu_connector_crash.log)
> 
> @petermetz I am able to run the failing tests related to Besu locally (`Cactus_CI / cactus-test-plugin-ledger-connector-besu` and `Cactus_CI / cactus-plugin-ledger-connector-besu`), could you confirm this is an issue caused by this code pls?
> 
> [get-balance-endpoint.test.ts.log](https://github.com/hyperledger/cacti/files/10695551/get-balance-endpoint.test.ts.log) [openapi-validation.test.ts.log](https://github.com/hyperledger/cacti/files/10695552/openapi-validation.test.ts.log)

@AndreAugusto11 If they pass locally then it's probably just a flake that it did not on the CI. I've done a rebase onto upstream main and force pushed it for you. Let's see how it goes now but I'll approve in the meantime because there's no other problem with it AFAICT.

**Review by petermetz — APPROVED** [review]
@AndreAugusto11 LGTM, thank you and sorry for the slow reviews!

**Review by petermetz — CHANGES_REQUESTED** [review]
@AndreAugusto11 @RafaelAPB The test is failing consistently now unfortunately. Please remedy and then it's good to go AFAICT!

Attaching the CI logs - fails the same way on my local machine so I'm pretty sure it's not a fluke.
[2023-04-03T01-53-43_PR_2251_besu_test_crash.log](https://github.com/hyperledger/cacti/files/11134292/2023-04-03T01-53-43_PR_2251_besu_test_crash.log)

**Comment by AndreAugusto11** [comment]
> @AndreAugusto11 @RafaelAPB The test is failing consistently now unfortunately. Please remedy and then it's good to go AFAICT!
> 
> Attaching the CI logs - fails the same way on my local machine so I'm pretty sure it's not a fluke. [2023-04-03T01-53-43_PR_2251_besu_test_crash.log](https://github.com/hyperledger/cacti/files/11134292/2023-04-03T01-53-43_PR_2251_besu_test_crash.log)

@petermetz thank you very much! This is weird because I have been trying to run those tests locally, and they pass. The changes are minimal, and I cannot understand where the problem might be. Do you have any idea?

[get-balance-endpoint.test.ts.log](https://github.com/hyperledger/cacti/files/11161605/get-balance-endpoint.test.ts.log)

**Review by petermetz — APPROVED** [review]
@AndreAugusto11 You were missing an `await` which looks like ended up creating a race condition - at least that's what I'm thinking for now. LGTM

**Pull request merged**
