### PR TITLE
feat(relay): configurable db_open retry mechanism added and in driver

### PR DESCRIPTION
**Pull request by sandeepnRES**
To manage concurrent accesses to a LevelDB instance so that protocols
don't fail because of temporary resource contention, added two env
variables in driver and config variables in relay to configure retry
mechanism while opening database:

- Max number of retries
- Backoff time in milli seconds.

Additionally upgraded go versions to v1.20 in publish workflows.

### CODE REVIEW

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by VRamakrishna** [comment]
@sandeepnRES Add a bit more description to your initial comment: Go version upgrades, need for the retry logic (to manage concurrent accesses to a LevelDB instance so that protocols don't fail because of temporary resource contention.)

**Review by VRamakrishna — APPROVED** [review]

**Comment by sandeepnRES** [comment]
Hi @petermetz I've modified the the PR description as per Rama's comments, and also added same in commit message.

**Review by petermetz — APPROVED** [review]
@sandeepnRES Thank you for making those changes! LGTM

**Pull request merged**
