### PR TITLE
feat(weaver/common): add data view protocol buffer spec & RFCs for Besu

### PR DESCRIPTION
**Pull request by VattiPraveen**
feat(weaver/common): add data view protocol buffer spec & RFCs for Besu

### CODE REVIEW

**Review by petermetz — CHANGES_REQUESTED** [review]
@VattiPraveen Thank you! Please do the following:
1. Squash into a single commit
2. Make sure the message uniquely describes what is being done - the current commit messages of "modified X" are not unique because literally every commit ever does exactly `that` so it's hard to read the commit log that way if too many of these slip into the log.
3. Once you've come up with a good commit message please sync that up to the PR title and the PR description as well.
4. Please read the contributing.md guide for further details

Other than my usual administrative nit-picks: LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@VattiPraveen I modified the PR title with a commit subject suggestion. If you agree then you can just make that your commit subject when you squash.

**Comment by VattiPraveen** [comment]
> feat(weaver/common): add data view protocol buffer spec & RFCs for Besu

Hi @petermetz.

I have made the changes as you suggested. Please review the PR.

**Review by sandeepnRES — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@VattiPraveen Nice! Now you just need to fix the DCO from what I can tell and then we should be good to go.

**Review by petermetz — APPROVED** [review]
@VattiPraveen LGTM, thank you!

**Pull request merged**
