### PR TITLE
tools(fabric2-all-in-one): fix multiple vulnerabilities - 2023-08-17

### PR DESCRIPTION
**Pull request by zondervancalvez**
Hard to dertermine which exact vulnerabilities will this be fixing because
other pull requests also upgrade the image version of this container in
the time while the pull request for this commit was open.

Nevertheless, it is an upgrade of versions and therefore some of the CVEs
are very likely getting addressed by it.

Fixes https://github.com/hyperledger/cacti/issues/2057

Co-authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Signed-off-by: zondervancalvez <zondervan.v.calvez@accenture.com>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

### CODE REVIEW

**Review by takeutak — APPROVED** [review]

**Comment by jagpreetsinghsasan** [comment]
Hi @zondervancalvez 
The Cactus_CI / ghcr-fabric2-all-in-one is failing (if you scroll down through the CI tests).

**Comment by zondervancalvez** [comment]
> Hi @zondervancalvez The Cactus_CI / ghcr-fabric2-all-in-one is failing (if you scroll down through the CI tests).

Issue is now addressed. Thanks.

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@zondervancalvez Thank you, this looks good to me, I'm just marking it down for a change request because I'd like to ask you to do a manual test of the new image (once the manual test passed please write that down here and then request a review again)

The test needs to make sure that at least one of the Fabric (v2) connector tests are passing fine with this image.
1. You build the image locally tagging it something like `faio`
2. You override one of the test cases to a) not pull the image b) use the `faio` image instead of the official ghcr.io ones
3. You run the test case (which now will be running against a container made from your image from this PR)
4. You verify that the test case has passed.

Please make sure to cover at least these test cases with the above methodology and the explicitly confirm in a follow-up comment that all of these test cases passed with your image:
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts

**Comment by petermetz** [comment]
@zondervancalvez Ping.

**Comment by zondervancalvez** [comment]
> @zondervancalvez Ping.

Hi @petermetz,
As of now, here are the status of the test cases:

- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts - **PASSED**
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts - **PASSED**
- packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts - **FAILING**

On the remaining failing test script, we are encountering issue on `ssh.connect`. See image below:
MicrosoftTeams-image (2)

As of now this is our blocker but we are trying to debug on the issue and the possible resolution.

**Comment by zondervancalvez** [comment]
Hi @petermetz,
Here are the status of the test cases using `faio` image that we created:

packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-endpoint-v1.test.ts - **PASSED**
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/deploy-cc-from-golang-source.test.ts - **PASSED**
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v2-2-x/run-transaction-with-identities.test.ts - **PASSED**

**Review by petermetz — APPROVED** [review]
@zondervancalvez Thank you very much for the manual confirmation! LGTM

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by petermetz — CHANGES_REQUESTED** [review]
@zondervancalvez Removing my approval until cross-org approval is secured (otherwise we might accidentally merge this because both me and Jagpreet have approved it already)

Please facilitate reviews from @takeutak @sandeepnRES @izuru0 @VRamakrishna and ping me when that's done (and then I can remove my change request which I just did to block until that happens)

**Review by takeutak — APPROVED** [review]

**Comment by takeutak** [comment]
@zondervancalvez @petermetz Very sorry for my late approval!  LGTM.

**Review by petermetz — APPROVED** [review]

**Comment by petermetz** [comment]
> @zondervancalvez @petermetz Very sorry for my late approval! LGTM.

@takeutak No worries at all! Thank you very much for the review!

**Review by petermetz — CHANGES_REQUESTED** [review]
@zondervancalvez Please use rebase instead of merge when updating your local branch to upstream/main

**Review by petermetz — CHANGES_REQUESTED** [review]
@zondervancalvez Please fix the build and re-execute the manual tests with the image built locally being used!

This is the error I'm getting:

```sh
$ DOCKER_BUILDKIT=1 docker build ./tools/docker/fabric-all-in-one/ -f ./tools/docker/fabric-all-in-one/Dockerfile_v2.x -t faio2x
[+] Building 33.5s (11/70)                                                                                                                                           docker:default
 => [internal] load build definition from Dockerfile_v2.x                                                                                                                      0.0s
 => => transferring dockerfile: 8.48kB                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/docker:24.0.2-dind                                                                                                          0.7s
 => [internal] load build context                                                                                                                                              0.0s
 => => transferring context: 5.00kB                                                                                                                                            0.0s
 => CACHED [ 1/67] FROM docker.io/library/docker:24.0.2-dind@sha256:1d148deae16a6bb4c89224c636e1fd1799a4d5925f545861ce0d7bea3a527b5d                                           0.0s
 => [ 2/67] RUN apk update                                                                                                                                                     1.3s
 => [ 3/67] RUN apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make                                                                                           19.8s
 => [ 4/67] RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python                                                                                          1.2s
 => [ 5/67] RUN python3 -m ensurepip                                                                                                                                           1.8s
 => [ 6/67] RUN pip3 install --no-cache --upgrade "pip>=21" setuptools                                                                                                         4.4s
 => ERROR [ 7/67] RUN pip install docker-compose                                                                                                                               4.3s
------
 > [ 7/67] RUN pip install docker-compose:
0.734 Collecting docker-compose
0.800   Downloading docker_compose-1.29.2-py2.py3-none-any.whl (114 kB)
0.827      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.8/114.8 kB 4.9 MB/s eta 0:00:00
0.930 Collecting PyYAML<6,>=3.10 (from docker-compose)
0.944   Downloading PyYAML-5.4.1.tar.gz (175 kB)
0.975      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 7.2 MB/s eta 0:00:00
1.104   Installing build dependencies: started
3.893   Installing build dependencies: finished with status 'done'
3.894   Getting requirements to build wheel: started
4.027   Getting requirements to build wheel: finished with status 'error'
4.035   error: subprocess-exited-with-error
4.035   
4.035   × Getting requirements to build wheel did not run successfully.
4.035   │ exit code: 1
4.035   ╰─> [68 lines of output]
4.035       /tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
4.035       !!
4.035       
4.035               ********************************************************************************
4.035               The license_file parameter is deprecated, use license_files instead.
4.035       
4.035               By 2023-Oct-30, you need to update your project and remove deprecated calls
4.035               or your builds will no longer be supported.
4.035       
4.035               See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
4.035               ********************************************************************************
4.035       
4.035       !!
4.035         parsed = self.parsers.get(option_name, lambda x: x)(value)
4.035       running egg_info
4.035       writing lib3/PyYAML.egg-info/PKG-INFO
4.035       writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
4.035       writing top-level names to lib3/PyYAML.egg-info/top_level.txt
4.035       Traceback (most recent call last):
4.035         File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
4.035           main()
4.035         File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
4.035           json_out['return_val'] = hook(**hook_input['kwargs'])
4.035                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4.035         File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
4.035           return hook(config_settings)
4.035                  ^^^^^^^^^^^^^^^^^^^^^
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
4.035           return self._get_build_requires(config_settings, requirements=['wheel'])
4.035                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
4.035           self.run_setup()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
4.035           exec(code, locals())
4.035         File "<string>", line 271, in <module>
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
4.035           return distutils.core.setup(**attrs)
4.035                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
4.035           return run_commands(dist)
4.035                  ^^^^^^^^^^^^^^^^^^
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
4.035           dist.run_commands()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
4.035           self.run_command(cmd)
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
4.035           super().run_command(command)
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
4.035           cmd_obj.run()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
4.035           self.find_sources()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
4.035           mm.run()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
4.035           self.add_defaults()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
4.035           sdist.add_defaults(self)
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
4.035           super().add_defaults()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
4.035           self._add_defaults_ext()
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
4.035           self.filelist.extend(build_ext.get_source_files())
4.035                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4.035         File "<string>", line 201, in get_source_files
4.035         File "/tmp/pip-build-env-_rezm8vb/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
4.035           raise AttributeError(attr)
4.035       AttributeError: cython_sources
4.035       [end of output]
4.035   
4.035   note: This error originates from a subprocess, and is likely not a problem with pip.
4.037 error: subprocess-exited-with-error
4.037 
4.037 × Getting requirements to build wheel did not run successfully.
4.037 │ exit code: 1
4.037 ╰─> See above for output.
4.037 
4.037 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile_v2.x:32
--------------------
  30 |     
  31 |     # Install Docker Compose which is a dependency of Fabric Samples
  32 | >>> RUN pip install docker-compose
  33 |     
  34 |     # Need git to clone the sources of the Fabric Samples repository from GitHub
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install docker-compose" did not complete successfully: exit code: 1
```

[2023-07-27-cacti-docker-container-fabric-2x-aio-build-crash.log](https://github.com/hyperledger/cacti/files/12186739/2023-07-27-cacti-docker-container-fabric-2x-aio-build-crash.log)

**Review by VRamakrishna — APPROVED** [review]

**Review by petermetz — APPROVED** [review]
I pushed the fixes, LGTM

**Pull request merged**
