### PR TITLE
chore(cleanup): deleted deprecated files and folders

### PR DESCRIPTION
**Pull request by VRamakrishna**
- Deleted 'docs-cactus' and 'weaver/docs' folders.
- Ensured that the latest contents in the above are reflected in the 'docs' folder.
- Updated MAINTAINERS.md file with contents from 'weaver/MAINTAINERS.md'.
- Deleted unnecessary 'MAINTAINERS.md' and 'CONTRIBUTING.md' in the 'weaver' folder.
- Fixed indentations and removed dead code in source files. Modified GitHub action to test docs build upon change

**Pull Request Requirements**
- [ ] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [ ] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [ ] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [ ] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [ ] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by sandeepnRES — APPROVED** [review]

**Comment by VRamakrishna** [comment]
@petermetz @sandeepnRES @outSH Sorry, I had to close another PR (https://github.com/hyperledger/cacti/pull/3370) and open this one as a replacement because of conflicts. You had already approved that one. Can you quickly review and approve this too?

**Comment by VRamakrishna** [comment]
Sorry, I need to fix this failing action: https://github.com/hyperledger/cacti/actions/runs/9856543186/job/27213767125?pr=3391. Please don't merge before I do that.

**Review by outSH — APPROVED** [review]

**Review by petermetz — APPROVED** [review]
@VRamakrishna Next time please fix the conflicts instead of duplicating the PR. The effort required is roughly the same but that way we avoid confusion and duplicate review effort from the maintainers.
If you struggle with git operations I'm happy to help!

**Comment by VRamakrishna** [comment]
> @VRamakrishna Next time please fix the conflicts instead of duplicating the PR. The effort required is roughly the same but that way we avoid confusion and duplicate review effort from the maintainers. If you struggle with git operations I'm happy to help!

I'll do that. Sorry for the extra work. The closure of the older PR was not intended, but it happened because of a mistake (lack of git knowledge, as you mentioned). I couldn't then find a way to reopen the PR, and it just felt simpler to open a new one.

**Comment by VRamakrishna** [comment]
@petermetz As I see, there are conflicts again. I'll try to follow the instructions to resolve them using the command line, as per the provided link.

**Comment by VRamakrishna** [comment]
(Update) fixed conflicts with help from @sandeepnRES .

**Pull request merged**
