### PR TITLE
chore(ci): try new builers

### PR DESCRIPTION
**Pull request by ryjones**
rename yaml->yml

update actions versions

Signed-off-by: Ry Jones <ry@linux.com>

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@ryjones Thank you, LGTM!

**Review by takeutak — APPROVED** [review]

**Review by petermetz — CHANGES_REQUESTED** [review]
@ryjones There are still some leftover yml -> yaml renames that need to be removed from the diff. I just checked out why the CodeQL is failing and it's also because of that (it only looks for it's own config file with .yml but not with .yaml)

Screenshot from 2023-04-14 00-33-18

Screenshot from 2023-04-14 00-33-04

**Comment by ryjones** [comment]
@petermetz I renamed that one file back to `.yml`

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Comment by sandeepnRES** [comment]
Hi @ryjones I think you missed updating runner for `.github/workflows/test_weaver-data-sharing.yaml`, because the runner that used there was `buildjet-4vcpu-ubuntu-2204`. I don't know if this was intentional, hence asking you here.

**Review by petermetz — APPROVED** [review]
@ryjones LGTM, thank you!

**Pull request merged**
