### PR TITLE
docs: add Pull Request Template

### PR DESCRIPTION
**Pull request by ruzell22**
Checkbox is updated so it will reflect as expected.

fixes: #91
related to: #2708

Signed-off-by: ruzell22 <ruzell.vince.aquino@accenture.com>

### CODE REVIEW

**Review by jagpreetsinghsasan — CHANGES_REQUESTED** [review]
The code isnt rendered correctly: https://github.com/ruzell22/cactus/blob/prtemplate91/PULL_REQUEST_TEMPLATE.md (No new lines)

You can install `Markdown All in One` extension in vscode and then press `Ctrl` + `Shift` + V to check the rendered output

**Review by petermetz — COMMENTED** [review]
^^ +1

**Comment by ruzell22** [comment]
Hello @jagpreetsinghsasan @petermetz , pushed a changed and the md file is now displaying the checkboxes as expected.
https://github.com/ruzell22/cactus/blob/prtemplate91/PULL_REQUEST_TEMPLATE.md
image

**Review by jagpreetsinghsasan — APPROVED** [review]
LGTM

**Review by petermetz — COMMENTED** [review]
@ruzell22 LGTM - but please add a `[skip ci]` declaration to the commit message so that we are not burning money on the CI for docs (the check that cancels the CI run if it's docs only is still not working so we have to try and pay some attention to this manually unfortunately.

**Comment by ruzell22** [comment]
@petermetz noted on that Peter, thank you. I have updated the commit message with `[skip ci]` .

**Review by sandeepnRES — APPROVED** [review]

**Pull request merged**
