### PR TITLE
feat(connector-chia): add plugin implementation #1634

### PR DESCRIPTION
**Pull request by RajGM**
For #1634 

chia-test-ledger.ts
plugin-ledger-connector-chia.ts
open API

### CODE REVIEW

**Comment by petermetz** [comment]
Closing due to inactivity, please free free to re-open later as needed.

**Comment by AndreAugusto11** [comment]
Hey @petermetz, what is the status of the Chia connector? I saw a project to develop it some months ago...Was it abandoned?

**Comment by AndreAugusto11** [comment]
@petermetz ok, thanks! And are you aware of how far this was from being completed?

**Comment by petermetz** [comment]
@AndreAugusto11 I think it got stuck somewhere in the beginning, probably at the phase where we create the all-in-one ledger for Chia

**Pull request closed without merging**
