### PR TITLE
feat(cactus-example-tcs-huawei): remove deprecated sample app

### LINKED ISSUE #3157: feat(cactus-example-tcs-huawei): remove deprecated sample app
**Is your feature request related to a problem? Please describe.**
`cactus-example-tcs-huawei` is using `cactus-plugin-ledger-connector-go-ethereum-socketio` and `cactus-plugin-ledger-connector-tcs-huawei-socketio`, both of them will be removed soon as well. Ths sample app can't exist without them.

**See #3155 for more details on motivation and future of this package!**

#### Deprecation and package removal is not final
If there's a need to bring some of these packages back, or if the package gets refactored so that it matches
the state of other cacti packages, then the package can be restored. Removed packages can still be accessed by checking-out the state of this repo before the removal (I'll add appropriate commits next to the removed plugins on the list as the PR get merged).

### PR DESCRIPTION
**Pull request by outSH**
- `cactus-example-tcs-huawei` is using `cactus-plugin-ledger-connector-go-ethereum-socketio` and `cactus-plugin-ledger-connector-tcs-huawei-socketio` which will be removed as well. Ths sample app can't exist on it's own.

Closes #3157
Part of #3155

**Pull Request Requirements**
- [x] Rebased onto `upstream/main` branch and squashed into single commit to help maintainers review it more efficient and to avoid spaghetti git commit graphs that obfuscate which commit did exactly what change, when and, why.
- [x] Have git sign off at the end of commit message to avoid being marked red. You can add `-s` flag when using `git commit` command. You may refer to this [link](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) for more information.
- [x] Follow the Commit Linting specification. You may refer to this [link](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#specification) for more information. 

**Character Limit**
- [x] Pull Request Title and Commit Subject must not exceed 72 characters (including spaces and special characters).
- [x] Commit Message per line must not exceed 80 characters (including spaces and special characters).

**A Must Read for Beginners**
For rebasing and squashing, here's a [must read guide](https://github.com/servo/servo/wiki/Beginner's-guide-to-rebasing-and-squashing) for beginners.

### CODE REVIEW

**Review by petermetz — APPROVED** [review]
@outSH LGTM and thank you for the PR!

I just wanted to give some more context around this:
We are in a pickle because we've been waiting for some months now for the updates to come in on these packages but have run out of time to wait and so in the meantime we are just removing this code but that does not imply in any way that we are not happy to put it back as soon as it's ready for prime time.

I  wanted to make sure that this is loud and clear to all community members, contributors, etc. because without this context it might come off as the maintainers just unilaterally removing the hard work of others which is not the case of course!

**Review by petermetz — COMMENTED** [review]
@outSH  Just one more suggestion: I'd also put the clarification that you explained in the GitHub issue itself directly to the commit message so that it's guaranteed to be available as information to someone who is just browsing the commit log and trying to figure out the details.

**Review by jagpreetsinghsasan — COMMENTED** [review]
LGTM

**Comment by outSH** [comment]
@petermetz Done, I've added the following to the commit:

```
- This is not permanent - we'd love to bring the package back once the
    necessary refactors are done!
- See issue https://github.com/hyperledger/cacti/issues/3155 on github for more details on context and reasoning
    of this decision.
```

**Comment by petermetz** [comment]
> @petermetz Done, I've added the following to the commit:
> 
> ```
> - This is not permanent - we'd love to bring the package back once the
>     necessary refactors are done!
> - See issue https://github.com/hyperledger/cacti/issues/3155 on github for more details on context and reasoning
>     of this decision.
> ```

@outSH Looks good to me, thank you for adding the extra clarifications!

**Review by izuru0 — APPROVED** [review]
LGTM thanks

**Pull request merged**
