### PR TITLE
docs(example/cbdc): Migrate CBDC example frontend from JS to TS

### LINKED ISSUE #2817: docs(examples/cbdc): migrate frontend implementation from JS to TS
**Is your feature request related to a problem? Please describe.**
The frontend is written in JavaScript instead of Typescript. To be consistent with the rest of the codebase and the monorepo, the code should be migrated to Typescript.

@petermetz can assign this to me pls

### PR DESCRIPTION
**Pull request by AndreAugusto11**
Closes #2817
Depends on #2912

### CODE REVIEW

**Review by petermetz — COMMENTED** [review]
@AndreAugusto11 Thank you, this is looking great!

Ran into a little trouble when testing it out though: I tried to run the back-end's `start` script (in the file `examples/cactus-example-cbdc-bridging-backend/package.json` but it fails with: 

```sh
Executing task: yarn run start 

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '@hyperledger/cactus-plugin-odap-hermes/src/main/typescript/index'
Require stack:
- /workspaces/cacti/examples/cactus-example-cbdc-bridging-backend/dist/lib/main/typescript/cbdc-bridging-app.js
- /workspaces/cacti/examples/cactus-example-cbdc-bridging-backend/dist/lib/main/typescript/cbdc-bridging-app-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/workspaces/cacti/examples/cactus-example-cbdc-bridging-backend/dist/lib/main/typescript/cbdc-bridging-app.js:12:17)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/workspaces/cacti/examples/cactus-example-cbdc-bridging-backend/dist/lib/main/typescript/cbdc-bridging-app.js',
    '/workspaces/cacti/examples/cactus-example-cbdc-bridging-backend/dist/lib/main/typescript/cbdc-bridging-app-cli.js'
  ]
}

Node.js v20.9.0

 *  The terminal process "/usr/bin/bash '-c', 'yarn run start'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

Does this reproduce on your machine as well?

**Comment by AndreAugusto11** [comment]
Hey @petermetz, thanks. It seems like you're in the backend folder, not in the one with the frontend code 😀

**Comment by petermetz** [comment]
> Hey @petermetz, thanks. It seems like you're in the backend folder, not in the one with the frontend code 😀

@AndreAugusto11 I am, but shouldn't it still work though? Let me double check if it works on the main branch.

**Comment by AndreAugusto11** [comment]
> > Hey @petermetz, thanks. It seems like you're in the backend folder, not in the one with the frontend code 😀
> 
> @AndreAugusto11 I am, but shouldn't it still work though? Let me double check if it works on the main branch.

Oh, my bad! I thought you were trying to spin up the front end. Yes, I have the same issue, usually just run it using the command in the root folder `npm run start:example-cbdc-bridging-app`

**Comment by AndreAugusto11** [comment]
@petermetz it should be fixed now. The imports to the `odap-hermes` package were not correct. Thanks for catching that!

**Review by petermetz — APPROVED** [review]
@AndreAugusto11 My pleasure and thank you very much for the fix! LGTM!

**Review by outSH — APPROVED** [review]

**Pull request merged**
