### PR TITLE
feat(openssl): version upgrade to v0.10.48 in cactus-plugin-keychain-vault

### PR DESCRIPTION
**Pull request by Poonam1607**
…tements in cactus-plugin-keychain-vault package

### CODE REVIEW

**Comment by jagpreetsinghsasan** [comment]
@Poonam1607 thankyou for the PR
As far I can see in the changed files, there is no change of parenthesis anywhere.
So I am updating the PR title.
For the PR description and the commit message, please refer to our contribution guide.
You can also refer to one of my merged PR's for reference: https://github.com/hyperledger/cacti/pull/2272

**Review by jagpreetsinghsasan — CHANGES_REQUESTED** [review]
@Poonam1607 thankyou for the PR
As far I can see in the changed files, there is no change of parenthesis anywhere.
So I am updating the PR title.
For the PR description and the commit message, please refer to our contribution guide.
You can also refer to one of my merged PR's for reference: https://github.com/hyperledger/cacti/pull/2272

**Comment by Poonam1607** [comment]
> @Poonam1607 thankyou for the PR As far I can see in the changed files, there is no change of parenthesis anywhere. So I am updating the PR title. For the PR description and the commit message, please refer to our contribution guide. You can also refer to one of my merged PR's for reference: #2272

Thankyou @jagpreetsinghsasan for doing that! Also, is there anything else wrong with the commit? Some checks are failing, can you please review it?

**Comment by jagpreetsinghsasan** [comment]
@Poonam1607 the previous review comments I provided are still not fixed.
The DCO check is failing as you probably haven't signed off the commit.
To fix it you need to add the signed commit as `git commit -s -m ..`

**Comment by sandeepnRES** [comment]
@Poonam1607 Hi, Can you squash all the commits into one commit? After squashing, you can run `git commit --amend -s`, to sign the last commit.

**Comment by Poonam1607** [comment]
> @Poonam1607 Hi, Thank you for the PR, but there are few issues with PR, so it can't be merged yet.
> 
> I am updating the title again just to make it more unique. Can you create only one commit with the same changes, and use the PR title as commit message and also use `git commit -s` to sign off the commit.
> 
> Also squashing the commit is not possible, as there are some conflicts, so you will have to create same changes again in fresh branch/fork that is in sync with main. Make sure there are no `merge commits` in the PR.

I did the changes with a new PR - feat(openssl): version upgrade to v0.10.48 in cactus-plugin-keychain-vault #2412

**Pull request closed without merging**
